# Overview
Welcome to Tuwaiq Academy, a non-profit training institute in Saudi Arabia. With millions of applicants vying for limited seats in advanced AI programs, this challenge is your chance to revolutionize the allocation process. Your task is to build a predictive model that identifies top candidates likely to successfully complete the training program.

### Goal:
The goal of the competition is to develop an efficient model that sifts through the pool of applicants, pinpointing those with the highest likelihood of completing Tuwaiq Academy's rigorous training programs. By achieving this, you contribute to the strategic utilization of limited seats, ensuring they are granted to individuals your model identifies as having the best potential to excel in the program. Seize the challenge, make a lasting impact!

# Description
### Overview:
Tuwaiq Academy, a non-profit educational institute in the Kingdom of Saudi Arabia, is on a mission to advance AI and emerging technologies. With a surge in applications and limited seats for our coveted advanced programs, we invite you to participate in this competition for educational excellence.

### Objective:
In the face of millions of applicants, Tuwaiq Academy aims to streamline the selection process for our advanced training programs. Your challenge is to develop a predictive model that can accurately identify individuals with the highest likelihood of successfully completing the rigorous training curriculum.

### Why Participate:

* Impactful Contribution: Your efforts directly influence the strategic allocation of limited seats, ensuring they are granted to those most likely to excel in the program.
* Advancing Education: By participating in this competition, you become a key player in shaping the future of education, contributing to the growth of knowledge and expertise in the field.
### Key Details:

* Dataset: We provide registration information for accepted trainees in a variety of training programs, including a completion target column.
* Objective: Develop a robust model to identify candidates with the best potential for successful program completion.
* Outcome: The winning models will significantly enhance the efficiency of the selection process, allowing Tuwaiq Academy to optimize resource allocation and make a lasting impact on the education landscape.
### How to Win:

* Accuracy: Build a model that accurately predicts trainees' likelihood of completing the program.
* Innovation: Stand out by incorporating innovative approaches, algorithms, or features that elevate the predictive power of your model.
* Explanation: Provide insights into the factors driving your model's predictions, demonstrating a clear understanding of the problem.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Installing required Libraries:

In [105]:
import pandas as pd
import numpy as np

# Exploratory Data Analysis (EDA)

In [106]:
df=pd.read_csv('test.csv')
df

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,أنثى,منطقة الرياض,الرياض,451d680f-e067-41c0-a998-6b3da3963bca,CAUF,SWPS,تقليدية,متوسط,...,5,لا,البكالوريوس,علوم الحاسب الالي,NaN,3.72,4.0,خريج,NaN,NaN
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,أنثى,منطقة الرياض,الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,PCRF,تقليدية,مبتدئ,...,19,لا,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.00,4.0,NaN,NaN,NaN
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,أنثى,منطقة الرياض,الرياض,03ec0d20-11cd-49bf-9b54-de5d12d4bd76,CAUF,SWPS,NaN,NaN,...,12,نعم,البكالوريوس,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,3.72,5.0,موظف,دوام كامل,Yes
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,أنثى,منطقة الرياض,الرياض,4ad7a7dc-abcf-43fa-b2e3-07095e083661,PCRF,PCRF,NaN,متقدم,...,5,نعم,البكالوريوس,Biology,NaN,4.47,5.0,غير موظف,NaN,NaN
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,أنثى,منطقة الرياض,الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,NaN,داعمة,متقدم,...,33,نعم,الدبلوم,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.46,5.0,غير موظف,دوام كامل,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,ذكر,منطقة الرياض,الرياض,1b546d80-2ed0-42e6-9867-61b3d2f92d50,GRST,INFA,NaN,متوسط,...,5,نعم,البكالوريوس,علوم حاسب,NaN,2.55,5.0,موظف,NaN,NaN
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,ذكر,منطقة الرياض,الرياض,aa87165d-cbde-4453-baca-1c8c03775e39,CAUF,CRDP,داعمة,مبتدئ,...,47,نعم,البكالوريوس,الهندسة الكهربائية,الهندسة والتصنيع والبناء,3.00,4.0,NaN,NaN,NaN
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,ذكر,منطقة الرياض,الرياض,c49987af-b421-4b88-b36a-a0ec91d95aa3,GRST,INFA,تقليدية,متوسط,...,5,نعم,البكالوريوس,شبكات حاسب,NaN,3.00,5.0,موظف,NaN,NaN
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,أنثى,منطقة الرياض,الرياض,899795e1-7bf3-46d0-a58e-824d4033f6da,PCRF,PCRF,تقليدية,متوسط,...,173,لا,البكالوريوس,نظم معلومات حاسوبية,NaN,4.12,5.0,غير موظف,NaN,NaN
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,ذكر,منطقة الرياض,الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,PCRF,تقليدية,مبتدئ,...,12,نعم,البكالوريوس,هندسة برمجيات,NaN,4.55,5.0,خريج,NaN,NaN

In [107]:
df.shape

(818, 23)

In [108]:
df.describe()

,Age,Program Days,University Degree Score,University Degree Score System
count,804.000000,818.000000,807.000000,807.000000
mean,26.675373,19.496333,8.406061,9.736059
std,5.462686,30.878220,19.588729,21.166854
min,18.000000,3.000000,0.000000,4.000000
25%,23.000000,5.000000,3.395000,5.000000
50%,25.000000,12.000000,4.000000,5.000000
75%,29.000000,19.000000,4.505000,5.000000
max,58.000000,292.000000,100.000000,100.000000

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 818 entries, 0 to 817
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Student ID                      818 non-null    object
 1   Age                             804 non-null    float64
 2   Gender                          818 non-null    object
 3   Home Region                     817 non-null    object
 4   Home City                       817 non-null    object
 5   Program ID                      818 non-null    object
 6   Program Main Category Code      818 non-null    object
 7   Program Sub Category Code       703 non-null    object
 8   Technology Type                 454 non-null    object
 9   Program Skill Level             618 non-null    object
 10  Program Presentation Method     818 non-null    object
 11  Program Start Date              818 non-null    object
 12  Program End Date                818 non-null    object
 13  Program Days                    818 non-null    int64
 14  Completed Degree                818 non-null    object
 15  Level of Education              815 non-null    object
 16  Education Speaciality           781 non-null    object
 17  College                         326 non-null    object
 18  University Degree Score         807 non-null    float64
 19  University Degree Score System  807 non-null    float64
 20  Employment Status               748 non-null    object
 21  Job Type                        237 non-null    object
 22  Still Working                   237 non-null    object
dtypes: float64(3), int64(1), object(19)
memory usage: 147.1+ KB

## Removing Duplicates

In [110]:
for i in df.columns:
    print(df[i].value_counts())
    print("---------------------")
# The first ID have been recorded for 3 times, we will check if the data have dublicates or not.

Student ID
19018c51-6a35-40da-a78c-2b26ed1e0728    3
8e198172-5f1d-4612-974e-aad81442bc0a    3
638e61d4-cda8-4637-b3eb-20c39cb29ef9    2
511c4ea9-8728-4ce6-a98c-350040ff2cf6    2
37321139-ee76-4be2-a034-f93e2b678f4e    2
                                       ..
36f9da7e-8984-4567-85a7-3700877e7e76    1
52221506-f0c7-4aa5-ae57-681051f90f15    1
9b992af9-8789-44f9-993e-dcbe3bef806d    1
3b52dbd3-403c-46ed-89ff-616c959781c9    1
4a15a037-f5f4-4947-8a67-9f28494a6f26    1
Name: count, Length: 780, dtype: int64
---------------------
Age
23.0    120
24.0     93
25.0     76
22.0     70
26.0     49
27.0     48
28.0     45
21.0     39
29.0     35
31.0     29
30.0     28
20.0     25
32.0     24
36.0     15
35.0     14
33.0     14
37.0     12
38.0     12
19.0     11
34.0      9
40.0      5
39.0      5
41.0      5
43.0      4
44.0      4
42.0      4
18.0      4
48.0      2
58.0      1
45.0      1
50.0      1
Name: count, dtype: int64
---------------------
Gender
أنثى    482
ذكر     336
Name: count, dtype: int64
---------------------
Home Region
منطقة الرياض             610
منطقة مكة المكرمة         79
المنطقة الشرقية           44
منطقة عسير                20
منطقة المدينة المنورة     15
منطقة القصيم              13
منطقة تبوك                 9
منطقة الجوف                8
منطقة الحدود الشمالية      5
منطقة جازان                5
منطقة الباحة               5
منطقة نجران                2
منطقة حائل                 2
Name: count, dtype: int64
---------------------
Home City
الرياض             599
جدة                 42
الجبيل              13
المدينة المنورة     12
مكة المكرمة         11
العاصمة المقدسة     10
الدمام               9
أبها                 8
بريدة                8
الطائف               8
تبوك                 7
سكاكا                7
الخبر                7
خميس مشيط            6
الهفوف               6
الباحة               5
القنفذة              4
عرعر                 4
الرس                 3
القطيف               3
بقيق                 3
المزاحمية            3
ينبع                 2
الدلم                2
المجمعة              2
حائل                 2
الخرج                2
محايل عسير           2
املج                 2
محايل                2
تربة                 2
رابغ                 1
سراة عبيدة           1
الدائر               1
السليل               1
رفحاء                1
الجموم               1
الظهران              1
نجران                1
عيون الجواء          1
أحد رفيدة            1
حفر الباطن           1
شرورة                1
جيزان                1
طبرجل                1
عنيزة                1
النعيرية             1
الحريملاء            1
جازان                1
العلا                1
أبو عريش             1
بيش                  1
Name: count, dtype: int64
---------------------
Program ID
ab263106-20a8-42aa-9626-278e62ae3a49    15
321e4dc8-c3c4-4173-bca5-59a0bd9f327c    13
e006900d-05a9-4c2b-a36f-0ffb9fce44cd    12
0d6336e2-4a79-4c32-8f15-073f9a4f6976    12
774699c7-15e8-484e-9045-efe5905866aa    10
                                        ..
a5a9e969-2d2d-4a17-a8e9-b1589d970847     1
ce173b66-cd22-4a7a-9cb5-c872f6942f50     1
bb30a929-46df-4648-9224-4d7739bdb61f     1
ee8edc03-54db-45ad-9417-9e7df440c8d6     1
aa87165d-cbde-4453-baca-1c8c03775e39     1
Name: count, Length: 211, dtype: int64
---------------------
Program Main Category Code
CAUF    284
PCRF    216
APMR    174
TOSL     56
GRST     32
ABIR     23
INFA     21
SERU      6
QWLM      4
DTFH      2
Name: count, dtype: int64
---------------------
Program Sub Category Code
SWPS    217
PCRF    216
SRTA     97
INFA     69
TOSL     32
ERST     25
CRDP     23
KLTM     15
QTDY      6
ASCW      3
Name: count, dtype: int64
---------------------
Technology Type
تقليدية    355
داعمة       51
ناشئة       48
Name: count, dtype: int64
---------------------
Program Skill Level
متوسط    282
مبتدئ    260
متقدم     76
Name: count, dtype: int64
---------------------
Program Presentation Method
حضوري     616
عن بعد    202
Name: count, dtype: int64
---------------------
Program Start Date
2023-04-02    41
2023-07-23    38
2023-05-07    35
2023-05-14    34
2023-07-16    32
              ..
2022-07-03     2
2022-11-13     2
2023-04-09     1
2022-12-11     1
2022-09-21     1
Name: count, Length: 74, dtype: int64
---------------------
Program End Date
2023-04-06    41
2023-09-14    36
2023-06-22    32
2023-03-02    31
2023-03-16    26
              ..
2023-06-06     2
2024-01-11     2
2023-08-31     1
2022-09-25     1
2022-10-27     1
Name: count, Length: 83, dtype: int64
---------------------
Program Days
5      346
12     210
54      66
19      46
26      38
33      21
4       16
173      9
44       8
40       7
47       6
59       5
61       5
9        5
25       4
292      4
20       3
10       3
80       3
135      3
21       3
3        3
96       2
66       2
Name: count, dtype: int64
---------------------
Completed Degree
نعم    639
لا     179
Name: count, dtype: int64
---------------------
Level of Education
البكالوريوس    660
الماجستير       69
الدبلوم         44
ثانوي           36
الدكتوراه        5
متوسط            1
Name: count, dtype: int64
---------------------
Education Speaciality
علوم الحاسبات          133
تقنية المعلومات         98
علوم حاسب               55
نظم المعلومات           47
تقنية معلومات           25
                      ...
تسويق                    1
العلوم في الرياضيات      1
هندسة إلكترونيات         1
حاسب نظم معلومات         1
شبكات حاسب               1
Name: count, Length: 210, dtype: int64
---------------------
College
تكنولوجيا الاتصالات والمعلومات         291
الأعمال والإدارة والقانون               17
الفنون والعلوم الإنسانية                 6
العلوم الاجتماعية والصحافة والإعلام      4
التعليم                                  3
الهندسة والتصنيع والبناء                 3
العلوم الطبيعية والرياضيات والإحصاء      2
Name: count, dtype: int64
---------------------
University Degree Score
4.00    127
3.00     67
4.50     18
5.00     15
2.00     13
       ...
4.49      1
4.81      1
3.19      1
3.21      1
2.63      1
Name: count, Length: 243, dtype: int64
---------------------
University Degree Score System
5.0      597
4.0      168
100.0     42
Name: count, dtype: int64
---------------------
Employment Status
موظف           350
طالب           133
غير موظف       131
خريج           119
موظف - طالب     11
عمل حر           4
Name: count, dtype: int64
---------------------
Job Type
دوام كامل    160
تدريب         63
دوام جزئي     10
تطوع           4
Name: count, dtype: int64
---------------------
Still Working
Yes    141
No      96
Name: count, dtype: int64
---------------------

In [111]:
df.loc[df['Student ID'] == '19018c51-6a35-40da-a78c-2b26ed1e0728']
# the same student showed in the dataset but the other information is different, this means the student is signed 9 times for different programs(data is not duplicated)

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working
11,19018c51-6a35-40da-a78c-2b26ed1e0728,25.0,ذكر,منطقة الرياض,الرياض,c1ade348-9775-4501-b050-252d5c5e6468,CAUF,SWPS,تقليدية,مبتدئ,...,5,نعم,البكالوريوس,تقنية المعلومات,NaN,4.0,5.0,خريج,NaN,NaN
24,19018c51-6a35-40da-a78c-2b26ed1e0728,25.0,ذكر,منطقة الرياض,الرياض,aee3a7b8-28ea-4b9d-963f-2f1413b81c04,PCRF,PCRF,NaN,متوسط,...,12,نعم,البكالوريوس,تقنية المعلومات,NaN,4.0,5.0,خريج,NaN,NaN
684,19018c51-6a35-40da-a78c-2b26ed1e0728,25.0,ذكر,منطقة الرياض,الرياض,321e4dc8-c3c4-4173-bca5-59a0bd9f327c,PCRF,PCRF,تقليدية,متوسط,...,12,نعم,البكالوريوس,تقنية المعلومات,NaN,4.0,5.0,خريج,NaN,NaN

In [112]:
df.duplicated().sum()
# Data shows that there is Identical rows, so we will need to delete the duplicates

4

In [113]:
# print the rows with duplicate information (sorted) to check that there is a true duplication
duplicated = df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())
duplicated

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working
215,70b9066f-f253-48a5-b30d-cdffa6fe7185,33.0,ذكر,منطقة الرياض,الرياض,321e4dc8-c3c4-4173-bca5-59a0bd9f327c,PCRF,PCRF,تقليدية,متوسط,...,12,نعم,البكالوريوس,نظم المعلومات,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,موظف,دوام كامل,Yes
495,70b9066f-f253-48a5-b30d-cdffa6fe7185,33.0,ذكر,منطقة الرياض,الرياض,321e4dc8-c3c4-4173-bca5-59a0bd9f327c,PCRF,PCRF,تقليدية,متوسط,...,12,نعم,البكالوريوس,نظم المعلومات,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,موظف,دوام كامل,Yes
712,88bb585d-20b3-4c55-adfe-85606cc3d32e,21.0,ذكر,منطقة الرياض,الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,NaN,داعمة,متقدم,...,33,نعم,البكالوريوس,علوم الحاسبات,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,طالب,NaN,NaN
734,88bb585d-20b3-4c55-adfe-85606cc3d32e,21.0,ذكر,منطقة الرياض,الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,NaN,داعمة,متقدم,...,33,نعم,البكالوريوس,علوم الحاسبات,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,طالب,NaN,NaN
38,9a9a9fd0-8605-4136-817e-456b89d98d53,32.0,ذكر,منطقة الرياض,الرياض,3dd29418-5f9d-4f1f-88bd-15beb922c745,APMR,NaN,NaN,متوسط,...,19,لا,الماجستير,ادارة أعمال,NaN,4.83,5.0,موظف,NaN,NaN
409,9a9a9fd0-8605-4136-817e-456b89d98d53,32.0,ذكر,منطقة الرياض,الرياض,3dd29418-5f9d-4f1f-88bd-15beb922c745,APMR,NaN,NaN,متوسط,...,19,لا,الماجستير,ادارة أعمال,NaN,4.83,5.0,موظف,NaN,NaN
310,d667a01b-9800-4d10-8c00-3ae9624b19ac,23.0,ذكر,منطقة الرياض,الرياض,7820fea0-6794-4b09-a31c-addee650e67c,CAUF,SWPS,داعمة,مبتدئ,...,12,نعم,البكالوريوس,علوم الحاسب,NaN,3.39,5.0,موظف,NaN,NaN
418,d667a01b-9800-4d10-8c00-3ae9624b19ac,23.0,ذكر,منطقة الرياض,الرياض,7820fea0-6794-4b09-a31c-addee650e67c,CAUF,SWPS,داعمة,مبتدئ,...,12,نعم,البكالوريوس,علوم الحاسب,NaN,3.39,5.0,موظف,NaN,NaN

In [114]:
# removing duplicates
df.drop_duplicates(inplace=True)

df.shape

(814, 23)

## Changing date format

In [115]:
df['Program Start Date']=pd.to_datetime(df['Program Start Date'])
df['Program End Date']=pd.to_datetime(df['Program End Date'])

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 814 entries, 0 to 817
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Student ID                      814 non-null    object
 1   Age                             800 non-null    float64
 2   Gender                          814 non-null    object
 3   Home Region                     813 non-null    object
 4   Home City                       813 non-null    object
 5   Program ID                      814 non-null    object
 6   Program Main Category Code      814 non-null    object
 7   Program Sub Category Code       701 non-null    object
 8   Technology Type                 451 non-null    object
 9   Program Skill Level             614 non-null    object
 10  Program Presentation Method     814 non-null    object
 11  Program Start Date              814 non-null    datetime64[ns]
 12  Program End Date                814 non-null    datetime64[ns]
 13  Program Days                    814 non-null    int64
 14  Completed Degree                814 non-null    object
 15  Level of Education              811 non-null    object
 16  Education Speaciality           777 non-null    object
 17  College                         324 non-null    object
 18  University Degree Score         803 non-null    float64
 19  University Degree Score System  803 non-null    float64
 20  Employment Status               744 non-null    object
 21  Job Type                        236 non-null    object
 22  Still Working                   236 non-null    object
dtypes: datetime64[ns](2), float64(3), int64(1), object(17)
memory usage: 152.6+ KB

## Fixing Nulls

In [117]:
df.isna().sum()

Student ID                          0
Age                                14
Gender                              0
Home Region                         1
Home City                           1
Program ID                          0
Program Main Category Code          0
Program Sub Category Code         113
Technology Type                   363
Program Skill Level               200
Program Presentation Method         0
Program Start Date                  0
Program End Date                    0
Program Days                        0
Completed Degree                    0
Level of Education                  3
Education Speaciality              37
College                           490
University Degree Score            11
University Degree Score System     11
Employment Status                  70
Job Type                          578
Still Working                     578
dtype: int64

In [118]:
# Age:
df['Age'].value_counts()

Age
23.0    119
24.0     93
25.0     76
22.0     70
26.0     49
27.0     48
28.0     45
21.0     38
29.0     35
31.0     29
30.0     28
20.0     25
32.0     23
36.0     15
35.0     14
33.0     13
37.0     12
38.0     12
19.0     11
34.0      9
40.0      5
39.0      5
41.0      5
43.0      4
44.0      4
42.0      4
18.0      4
48.0      2
58.0      1
45.0      1
50.0      1
Name: count, dtype: int64

In [119]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Age'].value_counts()

/var/folders/ry/nygdyncx27z9hfs4blrkchjm0000gn/T/ipykernel_6686/514352096.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

Age
23.0    119
24.0     93
25.0     90
22.0     70
26.0     49
27.0     48
28.0     45
21.0     38
29.0     35
31.0     29
30.0     28
20.0     25
32.0     23
36.0     15
35.0     14
33.0     13
37.0     12
38.0     12
19.0     11
34.0      9
40.0      5
39.0      5
41.0      5
43.0      4
44.0      4
42.0      4
18.0      4
48.0      2
58.0      1
45.0      1
50.0      1
Name: count, dtype: int64

In [120]:
# Level of Education
df['Level of Education'].value_counts()

Level of Education
البكالوريوس    657
الماجستير       68
الدبلوم         44
ثانوي           36
الدكتوراه        5
متوسط            1
Name: count, dtype: int64

In [121]:
df['Level of Education'].fillna(df['Level of Education'].mode().iloc[0], inplace=True)
df['Level of Education'].value_counts()

/var/folders/ry/nygdyncx27z9hfs4blrkchjm0000gn/T/ipykernel_6686/2953953701.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Level of Education'].fillna(df['Level of Education'].mode().iloc[0], inplace=True)

Level of Education
البكالوريوس    660
الماجستير       68
الدبلوم         44
ثانوي           36
الدكتوراه        5
متوسط            1
Name: count, dtype: int64

In [122]:
df.head()

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,أنثى,منطقة الرياض,الرياض,451d680f-e067-41c0-a998-6b3da3963bca,CAUF,SWPS,تقليدية,متوسط,...,5,لا,البكالوريوس,علوم الحاسب الالي,NaN,3.72,4.0,خريج,NaN,NaN
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,أنثى,منطقة الرياض,الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,PCRF,تقليدية,مبتدئ,...,19,لا,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.00,4.0,NaN,NaN,NaN
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,أنثى,منطقة الرياض,الرياض,03ec0d20-11cd-49bf-9b54-de5d12d4bd76,CAUF,SWPS,NaN,NaN,...,12,نعم,البكالوريوس,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,3.72,5.0,موظف,دوام كامل,Yes
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,أنثى,منطقة الرياض,الرياض,4ad7a7dc-abcf-43fa-b2e3-07095e083661,PCRF,PCRF,NaN,متقدم,...,5,نعم,البكالوريوس,Biology,NaN,4.47,5.0,غير موظف,NaN,NaN
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,أنثى,منطقة الرياض,الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,NaN,داعمة,متقدم,...,33,نعم,الدبلوم,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.46,5.0,غير موظف,دوام كامل,No

In [123]:
# Sub Category
main_sub_categories = df.groupby('Program Main Category Code')['Program Sub Category Code']\
                       .apply(lambda x: x.astype(str).unique())
print(main_sub_categories)

Program Main Category Code
ABIR                            [INFA, nan]
APMR    [SRTA, QTDY, nan, KLTM, SWPS, ASCW]
CAUF                [SWPS, nan, ERST, CRDP]
DTFH                                  [nan]
GRST                                 [INFA]
INFA                                 [INFA]
PCRF                                 [PCRF]
QWLM                                  [nan]
SERU                           [INFA, ERST]
TOSL                            [nan, TOSL]
Name: Program Sub Category Code, dtype: object

In [124]:
def fill_sub_category(row):
    main_category = row['Program Main Category Code']
    sub_categories = row['Program Sub Category Code']

    # Handle case where sub_categories is a single NaN float
    if pd.isna(sub_categories):
        return [main_category]

    # Ensure sub_categories is always treated as a list
    if not isinstance(sub_categories, list):
        sub_categories = [sub_categories]

    # If all values are nan, fill with main category
    if all(pd.isna(x) for x in sub_categories):
        return [main_category] * len(sub_categories)

    # Replace nan values with first non-nan value if exists, otherwise main category
    first_non_nan = next((x for x in sub_categories if not pd.isna(x)), main_category)
    return [first_non_nan if pd.isna(x) else x for x in sub_categories]

# Apply the function to fill nan values
df['Program Sub Category Code'] = df.apply(fill_sub_category, axis=1)

In [125]:
main_sub_categories = df.groupby('Program Main Category Code')['Program Sub Category Code']\
                       .apply(lambda x: x.astype(str).unique())
print(main_sub_categories)

Program Main Category Code
ABIR                                 [['INFA'], ['ABIR']]
APMR    [['SRTA'], ['QTDY'], ['APMR'], ['KLTM'], ['SWP...
CAUF             [['SWPS'], ['CAUF'], ['ERST'], ['CRDP']]
DTFH                                           [['DTFH']]
GRST                                           [['INFA']]
INFA                                           [['INFA']]
PCRF                                           [['PCRF']]
QWLM                                           [['QWLM']]
SERU                                 [['INFA'], ['ERST']]
TOSL                                           [['TOSL']]
Name: Program Sub Category Code, dtype: object

In [126]:
df.isnull().sum()

Student ID                          0
Age                                 0
Gender                              0
Home Region                         1
Home City                           1
Program ID                          0
Program Main Category Code          0
Program Sub Category Code           0
Technology Type                   363
Program Skill Level               200
Program Presentation Method         0
Program Start Date                  0
Program End Date                    0
Program Days                        0
Completed Degree                    0
Level of Education                  0
Education Speaciality              37
College                           490
University Degree Score            11
University Degree Score System     11
Employment Status                  70
Job Type                          578
Still Working                     578
dtype: int64

In [ ]:
# Home Region, Home City
# There is only 1 null records in Home Region, and they are also nulls in Home City thought, we will drop them
df[df['Home Region'].isnull()]

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working
249,f6a1cc64-4468-496b-8605-2ef0acc707f5,25.0,ذكر,NaN,NaN,e006900d-05a9-4c2b-a36f-0ffb9fce44cd,APMR,[APMR],NaN,متوسط,...,44,نعم,البكالوريوس,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [128]:
df.dropna(subset=['Home Region'], inplace=True)

In [129]:
# Education Speaciality
# Since Tuwaiq academy provides a Program related to Computer Science,
# it is normal to have students who have Computer Science background to apply for, so we will fill the nulls with علوم الحاسبات
df['Education Speaciality'].value_counts()

Education Speaciality
علوم الحاسبات                          132
تقنية المعلومات                         98
علوم حاسب                               55
نظم المعلومات                           46
تقنية معلومات                           25
                                      ...
applied network systems engineering      1
تسويق                                    1
العلوم في الرياضيات                      1
هندسة إلكترونيات                         1
شبكات حاسب                               1
Name: count, Length: 210, dtype: int64

In [130]:
df['Education Speaciality'].fillna('علوم الحاسبات',inplace=True)

/var/folders/ry/nygdyncx27z9hfs4blrkchjm0000gn/T/ipykernel_6686/4096565206.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Education Speaciality'].fillna('علوم الحاسبات',inplace=True)

In [131]:
# نوحد مسميات التخصصات
import re
import pandas as pd

def normalize_specialty(s):
    if pd.isna(s):
        return s
    s = str(s).strip().lower()

    # --- Computer Science & IT ---
    # علوم حاسب (Computer Science)
    if re.search(r'علوم\s*حاس(ب|بات|وب|ب\s*آلي|ب\s*الآلي|ب\.|ب$)', s) or \
       re.search(r'computer\s*science|cs|computing|علوم\s*الحاسب', s):
        return 'علوم حاسب'

    # هندسة حاسب (Computer Engineering)
    if re.search(r'هندسة\s*حاس(ب|بات|وب|ب\s*آلي|ب\s*الآلي|ب\.)', s) or \
       re.search(r'computer\s*engineering|هندسة\s*الحاسب', s):
        return 'هندسة حاسب'

    # تقنية معلومات (IT)
    if re.search(r'تقن(ية|يه)\s*معلومات|تكنولوجيا\s*معلومات|information\s*technology|it\b', s):
        return 'تقنية معلومات'

    # نظم معلومات (Information Systems)
    if re.search(r'نظم\s*معلومات|information\s*system|is\b|mis\b', s):
        return 'نظم معلومات'

    # أمن سيبراني (Cybersecurity)
    if re.search(r'أمن\s*سيبراني|cyber\s*security|cybersecurity|الأمن\s*السيبراني', s):
        return 'أمن سيبراني'

    # هندسة برمجيات (Software Engineering)
    if re.search(r'هندسة\s*برمجيات|software\s*engineering', s):
        return 'هندسة برمجيات'

    # --- Engineering ---
    # هندسة كهربائية (Electrical Engineering)
    if re.search(r'هندسة\s*كهربائية|electrical\s*engineering', s):
        return 'هندسة كهربائية'

    # --- Business ---
    # إدارة أعمال (Business Administration)
    if re.search(r'إدارة\s*أعمال|ادارة\s*اعمال|business\s*administration|mba', s):
        return 'إدارة أعمال'

    # --- Miscellaneous ---
    # غير متخصص (Non-Specialized)
    if re.search(r'غير\s*متخصص|non\-specialized|لا\s*يوجد', s):
        return 'غير متخصص'

    # Default: Return original string (title-cased)
    return s.title()

# Apply to DataFrame

df['Education Speaciality'] = df['Education Speaciality'].apply(normalize_specialty)

In [132]:
df['Education Speaciality'].value_counts()

Education Speaciality
علوم حاسب            285
تقنية المعلومات       98
نظم معلومات           54
نظم المعلومات         46
تقنية معلومات         44
                    ...
تجارة الكترونية        1
Software Engineer      1
Computer Network       1
مالية                  1
شبكات حاسب             1
Name: count, Length: 143, dtype: int64

In [133]:
# College
# Since the data is about Tuwaiq academy, witch provides a computer science related courses, we will change the data into تكنولوجيا الاتصالات والمعلومات and غير ذلك,
# and fill the missing data with تكنولوجيا الاتصالات والمعلومات
df['College'].value_counts()

College
تكنولوجيا الاتصالات والمعلومات         289
الأعمال والإدارة والقانون               17
الفنون والعلوم الإنسانية                 6
العلوم الاجتماعية والصحافة والإعلام      4
التعليم                                  3
الهندسة والتصنيع والبناء                 3
العلوم الطبيعية والرياضيات والإحصاء      2
Name: count, dtype: int64

In [134]:
df['College'].fillna('تكنولوجيا الاتصالات والمعلومات', inplace=True)

df['College'] = df['College'].mask(
    df['College'] != 'تكنولوجيا الاتصالات والمعلومات',
    'غير ذلك'
)

df['College'].value_counts()

/var/folders/ry/nygdyncx27z9hfs4blrkchjm0000gn/T/ipykernel_6686/3326926096.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['College'].fillna('تكنولوجيا الاتصالات والمعلومات', inplace=True)

College
تكنولوجيا الاتصالات والمعلومات    778
غير ذلك                            35
Name: count, dtype: int64

In [135]:
df['Employment Status'] = df['Employment Status'].fillna(df['Employment Status'].mode()[0])

In [136]:
# ما نحتاجه لانه موجود Employment Status
df = df.drop('Still Working', axis=1)

In [137]:
df['University Degree Score'] = df['University Degree Score'].fillna(df['University Degree Score'].median())
df['University Degree Score System'] = df['University Degree Score System'].fillna(df['University Degree Score System'].mode()[0])

In [138]:
df.isna().sum()

Student ID                          0
Age                                 0
Gender                              0
Home Region                         0
Home City                           0
Program ID                          0
Program Main Category Code          0
Program Sub Category Code           0
Technology Type                   362
Program Skill Level               200
Program Presentation Method         0
Program Start Date                  0
Program End Date                    0
Program Days                        0
Completed Degree                    0
Level of Education                  0
Education Speaciality               0
College                             0
University Degree Score             0
University Degree Score System      0
Employment Status                   0
Job Type                          577
dtype: int64

In [139]:
mode_count =(df['Program Skill Level'] == 'متوسط').sum()
mode_count

279

In [140]:
df['Program Skill Level'].value_counts()

Program Skill Level
متوسط    279
مبتدئ    259
متقدم     75
Name: count, dtype: int64

In [141]:
#normalized score system
#عشان تكون المعدلات ادق
df['Degree_Score_Normalized'] = (
    df['University Degree Score'] 
    / df['University Degree Score System']
)

df['Degree_Score_Pct'] = df['Degree_Score_Normalized'] * 100
df.drop(columns=['Degree_Score_Normalized'], inplace=True)

In [142]:
df['Program ID'].value_counts()

Program ID
ab263106-20a8-42aa-9626-278e62ae3a49    15
0d6336e2-4a79-4c32-8f15-073f9a4f6976    12
321e4dc8-c3c4-4173-bca5-59a0bd9f327c    12
e006900d-05a9-4c2b-a36f-0ffb9fce44cd    11
774699c7-15e8-484e-9045-efe5905866aa    10
                                        ..
a5a9e969-2d2d-4a17-a8e9-b1589d970847     1
ce173b66-cd22-4a7a-9cb5-c872f6942f50     1
bb30a929-46df-4648-9224-4d7739bdb61f     1
ee8edc03-54db-45ad-9417-9e7df440c8d6     1
aa87165d-cbde-4453-baca-1c8c03775e39     1
Name: count, Length: 211, dtype: int64

In [143]:
df['Completed Degree'].value_counts()

Completed Degree
نعم    635
لا     178
Name: count, dtype: int64

In [144]:
df['Technology Type'].value_counts()

Technology Type
تقليدية    354
داعمة       49
ناشئة       48
Name: count, dtype: int64

In [145]:
df['Technology Type'].isna().sum()

362

In [ ]:
#we will filled the missing data in Technology Type with مفقود since its nearly half of the data
df['Technology Type'] = df['Technology Type'].fillna('مفقود')

In [147]:
df['Program Skill Level'].isna().sum()

200

In [148]:
##we will filled the missing data in Program Skill Level with مفقود
#we made all the nulls to مفقود because nulls doesnt apear while training and testing

df['Program Skill Level'] = df['Program Skill Level'].fillna('مفقود')
df

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,أنثى,منطقة الرياض,الرياض,451d680f-e067-41c0-a998-6b3da3963bca,CAUF,[SWPS],تقليدية,متوسط,...,5,لا,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,3.72,4.0,خريج,NaN,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,أنثى,منطقة الرياض,الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,[PCRF],تقليدية,مبتدئ,...,19,لا,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.00,4.0,موظف,NaN,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,أنثى,منطقة الرياض,الرياض,03ec0d20-11cd-49bf-9b54-de5d12d4bd76,CAUF,[SWPS],مفقود,مفقود,...,12,نعم,البكالوريوس,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,3.72,5.0,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,أنثى,منطقة الرياض,الرياض,4ad7a7dc-abcf-43fa-b2e3-07095e083661,PCRF,[PCRF],مفقود,متقدم,...,5,نعم,البكالوريوس,Biology,تكنولوجيا الاتصالات والمعلومات,4.47,5.0,غير موظف,NaN,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,أنثى,منطقة الرياض,الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,[TOSL],داعمة,متقدم,...,33,نعم,الدبلوم,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.46,5.0,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,ذكر,منطقة الرياض,الرياض,1b546d80-2ed0-42e6-9867-61b3d2f92d50,GRST,[INFA],مفقود,متوسط,...,5,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,2.55,5.0,موظف,NaN,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,ذكر,منطقة الرياض,الرياض,aa87165d-cbde-4453-baca-1c8c03775e39,CAUF,[CRDP],داعمة,مبتدئ,...,47,نعم,البكالوريوس,الهندسة الكهربائية,غير ذلك,3.00,4.0,موظف,NaN,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,ذكر,منطقة الرياض,الرياض,c49987af-b421-4b88-b36a-a0ec91d95aa3,GRST,[INFA],تقليدية,متوسط,...,5,نعم,البكالوريوس,شبكات حاسب,تكنولوجيا الاتصالات والمعلومات,3.00,5.0,موظف,NaN,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,أنثى,منطقة الرياض,الرياض,899795e1-7bf3-46d0-a58e-824d4033f6da,PCRF,[PCRF],تقليدية,متوسط,...,173,لا,البكالوريوس,نظم معلومات,تكنولوجيا الاتصالات والمعلومات,4.12,5.0,غير موظف,NaN,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,ذكر,منطقة الرياض,الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,[PCRF],تقليدية,مبتدئ,...,12,نعم,البكالوريوس,هندسة برمجيات,تكنولوجيا الاتصالات والمعلومات,4.55,5.0,خريج,NaN,91.0

In [149]:
df['Education Speaciality'].value_counts()

Education Speaciality
علوم حاسب            285
تقنية المعلومات       98
نظم معلومات           54
نظم المعلومات         46
تقنية معلومات         44
                    ...
تجارة الكترونية        1
Software Engineer      1
Computer Network       1
مالية                  1
شبكات حاسب             1
Name: count, Length: 143, dtype: int64

In [150]:
df.tail(20)

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
798,7581c89c-ff82-40dc-a3af-56ed6d9b4d9b,29.0,ذكر,منطقة الرياض,الرياض,c93ccd9b-76cc-4683-acec-d16064a65681,CAUF,[CAUF],مفقود,متقدم,...,5,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,3.13,4.0,موظف,NaN,78.25
799,ddea6cbe-20a0-4598-b9ce-73c39e604c03,27.0,أنثى,منطقة الجوف,سكاكا,5ab61376-f20b-4e5a-bce4-22b8890bbc2e,APMR,[SRTA],تقليدية,مبتدئ,...,5,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,3.75,5.0,غير موظف,تدريب,75.00
800,4b6cbd6b-45ff-4906-907c-c98e9d6f196f,20.0,أنثى,منطقة الرياض,الرياض,4185c029-c93a-49d0-87c3-fcede7b57048,CAUF,[CAUF],مفقود,مبتدئ,...,5,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,طالب,NaN,80.00
801,5439a6bd-1f9d-47c4-899b-c795ad5fd5c4,26.0,أنثى,منطقة مكة المكرمة,جدة,e58677d9-20ef-43a4-955e-e78e2989cc91,INFA,[INFA],مفقود,مفقود,...,12,نعم,البكالوريوس,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,3.60,5.0,موظف,دوام كامل,72.00
802,c68a72ea-c800-4c8a-a48e-9e43678dd371,27.0,ذكر,منطقة مكة المكرمة,جدة,6fa2fce7-a84d-48d7-b71b-99ae9bae7865,CAUF,[SWPS],تقليدية,متوسط,...,26,نعم,البكالوريوس,تقنية معلومات,تكنولوجيا الاتصالات والمعلومات,4.07,5.0,خريج,NaN,81.40
803,2c5e4be4-4a79-4de0-953b-36892a4acd4e,27.0,ذكر,منطقة الرياض,الرياض,9b4cedaa-fac0-4eac-aa4b-b05b6a0c97ff,PCRF,[PCRF],مفقود,متوسط,...,12,نعم,البكالوريوس,إدارة الشبكات,تكنولوجيا الاتصالات والمعلومات,3.38,5.0,موظف,دوام كامل,67.60
804,75e4fc60-1308-4454-b36f-637934508b2e,24.0,أنثى,منطقة تبوك,تبوك,daf89fda-a75f-487c-a30c-0b65de513e32,CAUF,[CAUF],مفقود,مبتدئ,...,5,لا,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,3.00,5.0,غير موظف,NaN,60.00
805,21242b23-9fdf-413b-8dda-d178ce01864c,23.0,ذكر,منطقة مكة المكرمة,القنفذة,cc8e4e42-65d5-4fa1-82f9-6c6c2d508b60,APMR,[SWPS],مفقود,متوسط,...,5,لا,البكالوريوس,رياضيات,تكنولوجيا الاتصالات والمعلومات,2.63,4.0,خريج,NaN,65.75
806,c7106923-becb-41e0-95da-905c61d6f861,21.0,أنثى,منطقة الرياض,الرياض,642f04b2-67f8-4403-98f1-c5c5755eb358,CAUF,[SWPS],داعمة,متوسط,...,5,لا,الدبلوم,برمجة وقواعد بيانات,تكنولوجيا الاتصالات والمعلومات,4.54,5.0,طالب,NaN,90.80
807,6816f4c0-c117-40f9-a46f-2c55e29b6d14,25.0,ذكر,منطقة الرياض,الرياض,0d12d5ef-7965-4a0d-a18c-7cc826c4f971,APMR,[SRTA],داعمة,مبتدئ,...,5,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,3.96,5.0,موظف,دوام كامل,79.20
808,61a64eba-6dbc-478c-a91c-db6e1ec10ef2,27.0,أنثى,منطقة الرياض,الرياض,2d5681bc-aa1c-4d85-bd5e-58f14bb9c317,INFA,[INFA],مفقود,مفقود,...,135,نعم,البكالوريوس,تقنية معلومات,تكنولوجيا الاتصالات والمعلومات,3.13,4.0,خريج,NaN,78.25
809,37321139-ee76-4be2-a034-f93e2b678f4e,27.0,أنثى,منطقة الرياض,الرياض,aee3a7b8-28ea-4b9d-963f-2f1413b81c04,PCRF,[PCRF],مفقود,متوسط,...,12,لا,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,4.50,5.0,موظف,NaN,90.00
810,d6c59c96-b18b-4971-8475-c7efb2cbc983,28.0,ذكر,منطقة الرياض,الرياض,5c04b39b-5895-46c9-b48a-a98ed9ae0d5a,TOSL,[TOSL],مفقود,متوسط,...,47,نعم,البكالوريوس,هندسة الشبكات والاتصالات,تكنولوجيا الاتصالات والمعلومات,3.30,5.0,غير موظف,NaN,66.00
811,742e3404-d5ba-4bd0-b060-1ba02f5d6e93,32.0,أنثى,منطقة الرياض,الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,[PCRF],تقليدية,مبتدئ,...,19,نعم,البكالوريوس,رياضيات,تكنولوجيا الاتصالات والمعلومات,2.30,5.0,غير موظف,NaN,46.00
812,d7a4c8b3-c79e-437a-8f7c-5a7d7808157d,22.0,ذكر,منطقة الرياض,الرياض,3488740a-30b9-45d0-a727-6633335e4216,PCRF,[PCRF],مفقود,متقدم,...,5,لا,ثانوي,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,89.00,100.0,طالب,NaN,89.00
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,ذكر,منطقة الرياض,الرياض,1b546d80-2ed0-42e6-9867-61b3d2f92d50,GRST,[INFA],مفقود,متوسط,...,5,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,2.55,5.0,موظف,NaN,51.00
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,ذكر,منطقة الرياض,الرياض,aa87165d-cbde-4453-baca-1c8c03775e39,CAUF,[CRDP],داعمة,مبتدئ,...,47,نعم,البكالوريوس,الهندسة الكهربائية,غير ذلك,3.00,4.0,موظف,NaN,75.00
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,ذكر,منطقة الرياض,الرياض,c49987af-b421-4b88-b36a-a0ec91d95aa3,GRST,[INFA],تقليدية,متوسط,...,5,نعم,البكالوريوس,شبكات حاسب,تكنولوجيا الاتصالات والمعلومات,3.00,5.0,موظف,NaN,60.00
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,أنثى,منطقة الرياض,الرياض,899795e1-7bf3-46d0-a58e-824d4033f6da,PCRF,[PCRF],تقليدية,متوسط,...,173,لا,البكالوريوس,نظم معلومات,تكنولوجيا الاتصالات والمعلومات,4.12,5.0,غير موظف,NaN,82.40
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,ذكر,منطقة الرياض,الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,[PCRF],تقليدية,مبتدئ,...,12,نعم,البكالوريوس,هندسة برمجيات,تكنولوجيا الاتصالات والمعلومات,4.55,5.0,خريج,NaN,91.00

In [152]:
##we will filled the missing data inJob Type with مفقود
df['Job Type'] = df['Job Type'].fillna('مفقود')
df

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,أنثى,منطقة الرياض,الرياض,451d680f-e067-41c0-a998-6b3da3963bca,CAUF,[SWPS],تقليدية,متوسط,...,5,لا,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,3.72,4.0,خريج,مفقود,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,أنثى,منطقة الرياض,الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,[PCRF],تقليدية,مبتدئ,...,19,لا,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.00,4.0,موظف,مفقود,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,أنثى,منطقة الرياض,الرياض,03ec0d20-11cd-49bf-9b54-de5d12d4bd76,CAUF,[SWPS],مفقود,مفقود,...,12,نعم,البكالوريوس,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,3.72,5.0,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,أنثى,منطقة الرياض,الرياض,4ad7a7dc-abcf-43fa-b2e3-07095e083661,PCRF,[PCRF],مفقود,متقدم,...,5,نعم,البكالوريوس,Biology,تكنولوجيا الاتصالات والمعلومات,4.47,5.0,غير موظف,مفقود,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,أنثى,منطقة الرياض,الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,[TOSL],داعمة,متقدم,...,33,نعم,الدبلوم,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.46,5.0,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,ذكر,منطقة الرياض,الرياض,1b546d80-2ed0-42e6-9867-61b3d2f92d50,GRST,[INFA],مفقود,متوسط,...,5,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,2.55,5.0,موظف,مفقود,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,ذكر,منطقة الرياض,الرياض,aa87165d-cbde-4453-baca-1c8c03775e39,CAUF,[CRDP],داعمة,مبتدئ,...,47,نعم,البكالوريوس,الهندسة الكهربائية,غير ذلك,3.00,4.0,موظف,مفقود,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,ذكر,منطقة الرياض,الرياض,c49987af-b421-4b88-b36a-a0ec91d95aa3,GRST,[INFA],تقليدية,متوسط,...,5,نعم,البكالوريوس,شبكات حاسب,تكنولوجيا الاتصالات والمعلومات,3.00,5.0,موظف,مفقود,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,أنثى,منطقة الرياض,الرياض,899795e1-7bf3-46d0-a58e-824d4033f6da,PCRF,[PCRF],تقليدية,متوسط,...,173,لا,البكالوريوس,نظم معلومات,تكنولوجيا الاتصالات والمعلومات,4.12,5.0,غير موظف,مفقود,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,ذكر,منطقة الرياض,الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,[PCRF],تقليدية,مبتدئ,...,12,نعم,البكالوريوس,هندسة برمجيات,تكنولوجيا الاتصالات والمعلومات,4.55,5.0,خريج,مفقود,91.0

In [153]:
df.isna().sum()

Student ID                        0
Age                               0
Gender                            0
Home Region                       0
Home City                         0
Program ID                        0
Program Main Category Code        0
Program Sub Category Code         0
Technology Type                   0
Program Skill Level               0
Program Presentation Method       0
Program Start Date                0
Program End Date                  0
Program Days                      0
Completed Degree                  0
Level of Education                0
Education Speaciality             0
College                           0
University Degree Score           0
University Degree Score System    0
Employment Status                 0
Job Type                          0
Degree_Score_Pct                  0
dtype: int64

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 813 entries, 0 to 817
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Student ID                      813 non-null    object
 1   Age                             813 non-null    float64
 2   Gender                          813 non-null    object
 3   Home Region                     813 non-null    object
 4   Home City                       813 non-null    object
 5   Program ID                      813 non-null    object
 6   Program Main Category Code      813 non-null    object
 7   Program Sub Category Code       813 non-null    object
 8   Technology Type                 813 non-null    object
 9   Program Skill Level             813 non-null    object
 10  Program Presentation Method     813 non-null    object
 11  Program Start Date              813 non-null    datetime64[ns]
 12  Program End Date                813 non-null    datetime64[ns]
 13  Program Days                    813 non-null    int64
 14  Completed Degree                813 non-null    object
 15  Level of Education              813 non-null    object
 16  Education Speaciality           813 non-null    object
 17  College                         813 non-null    object
 18  University Degree Score         813 non-null    float64
 19  University Degree Score System  813 non-null    float64
 20  Employment Status               813 non-null    object
 21  Job Type                        813 non-null    object
 22  Degree_Score_Pct                813 non-null    float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(16)
memory usage: 152.4+ KB

In [155]:
# encoding categorical variables
# find object columns
categorical_columns=list(df.select_dtypes(['object']).columns)
categorical_columns

['Student ID',
 'Gender',
 'Home Region',
 'Home City',
 'Program ID',
 'Program Main Category Code',
 'Program Sub Category Code',
 'Technology Type',
 'Program Skill Level',
 'Program Presentation Method',
 'Completed Degree',
 'Level of Education',
 'Education Speaciality',
 'College',
 'Employment Status',
 'Job Type']

In [156]:
import category_encoders as ce
encoder= ce.OneHotEncoder(cols='Gender',return_df=True,use_cat_names=True)

In [157]:
df=encoder.fit_transform(df)

In [158]:
df.drop(columns=['Gender_أنثى'], inplace=True)
df

,Student ID,Age,Gender_ذكر,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,0,منطقة الرياض,الرياض,451d680f-e067-41c0-a998-6b3da3963bca,CAUF,[SWPS],تقليدية,متوسط,...,5,لا,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,3.72,4.0,خريج,مفقود,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,0,منطقة الرياض,الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,[PCRF],تقليدية,مبتدئ,...,19,لا,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.00,4.0,موظف,مفقود,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,0,منطقة الرياض,الرياض,03ec0d20-11cd-49bf-9b54-de5d12d4bd76,CAUF,[SWPS],مفقود,مفقود,...,12,نعم,البكالوريوس,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,3.72,5.0,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,0,منطقة الرياض,الرياض,4ad7a7dc-abcf-43fa-b2e3-07095e083661,PCRF,[PCRF],مفقود,متقدم,...,5,نعم,البكالوريوس,Biology,تكنولوجيا الاتصالات والمعلومات,4.47,5.0,غير موظف,مفقود,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,0,منطقة الرياض,الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,[TOSL],داعمة,متقدم,...,33,نعم,الدبلوم,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.46,5.0,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,1,منطقة الرياض,الرياض,1b546d80-2ed0-42e6-9867-61b3d2f92d50,GRST,[INFA],مفقود,متوسط,...,5,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,2.55,5.0,موظف,مفقود,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,1,منطقة الرياض,الرياض,aa87165d-cbde-4453-baca-1c8c03775e39,CAUF,[CRDP],داعمة,مبتدئ,...,47,نعم,البكالوريوس,الهندسة الكهربائية,غير ذلك,3.00,4.0,موظف,مفقود,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,1,منطقة الرياض,الرياض,c49987af-b421-4b88-b36a-a0ec91d95aa3,GRST,[INFA],تقليدية,متوسط,...,5,نعم,البكالوريوس,شبكات حاسب,تكنولوجيا الاتصالات والمعلومات,3.00,5.0,موظف,مفقود,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,0,منطقة الرياض,الرياض,899795e1-7bf3-46d0-a58e-824d4033f6da,PCRF,[PCRF],تقليدية,متوسط,...,173,لا,البكالوريوس,نظم معلومات,تكنولوجيا الاتصالات والمعلومات,4.12,5.0,غير موظف,مفقود,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,1,منطقة الرياض,الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,[PCRF],تقليدية,مبتدئ,...,12,نعم,البكالوريوس,هندسة برمجيات,تكنولوجيا الاتصالات والمعلومات,4.55,5.0,خريج,مفقود,91.0

In [159]:
df.drop(columns=['Home City'], inplace=True)
df

,Student ID,Age,Gender_ذكر,Home Region,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,Program Presentation Method,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,0,منطقة الرياض,451d680f-e067-41c0-a998-6b3da3963bca,CAUF,[SWPS],تقليدية,متوسط,عن بعد,...,5,لا,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,3.72,4.0,خريج,مفقود,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,0,منطقة الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,[PCRF],تقليدية,مبتدئ,عن بعد,...,19,لا,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.00,4.0,موظف,مفقود,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,0,منطقة الرياض,03ec0d20-11cd-49bf-9b54-de5d12d4bd76,CAUF,[SWPS],مفقود,مفقود,عن بعد,...,12,نعم,البكالوريوس,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,3.72,5.0,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,0,منطقة الرياض,4ad7a7dc-abcf-43fa-b2e3-07095e083661,PCRF,[PCRF],مفقود,متقدم,حضوري,...,5,نعم,البكالوريوس,Biology,تكنولوجيا الاتصالات والمعلومات,4.47,5.0,غير موظف,مفقود,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,0,منطقة الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,[TOSL],داعمة,متقدم,حضوري,...,33,نعم,الدبلوم,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.46,5.0,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,1,منطقة الرياض,1b546d80-2ed0-42e6-9867-61b3d2f92d50,GRST,[INFA],مفقود,متوسط,حضوري,...,5,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,2.55,5.0,موظف,مفقود,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,1,منطقة الرياض,aa87165d-cbde-4453-baca-1c8c03775e39,CAUF,[CRDP],داعمة,مبتدئ,حضوري,...,47,نعم,البكالوريوس,الهندسة الكهربائية,غير ذلك,3.00,4.0,موظف,مفقود,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,1,منطقة الرياض,c49987af-b421-4b88-b36a-a0ec91d95aa3,GRST,[INFA],تقليدية,متوسط,حضوري,...,5,نعم,البكالوريوس,شبكات حاسب,تكنولوجيا الاتصالات والمعلومات,3.00,5.0,موظف,مفقود,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,0,منطقة الرياض,899795e1-7bf3-46d0-a58e-824d4033f6da,PCRF,[PCRF],تقليدية,متوسط,عن بعد,...,173,لا,البكالوريوس,نظم معلومات,تكنولوجيا الاتصالات والمعلومات,4.12,5.0,غير موظف,مفقود,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,1,منطقة الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,[PCRF],تقليدية,مبتدئ,حضوري,...,12,نعم,البكالوريوس,هندسة برمجيات,تكنولوجيا الاتصالات والمعلومات,4.55,5.0,خريج,مفقود,91.0

In [160]:
encoder= ce.OneHotEncoder(cols='College',return_df=True,use_cat_names=True)
df=encoder.fit_transform(df)
df

,Student ID,Age,Gender_ذكر,Home Region,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,Program Presentation Method,...,Completed Degree,Level of Education,Education Speaciality,College_تكنولوجيا الاتصالات والمعلومات,College_غير ذلك,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,0,منطقة الرياض,451d680f-e067-41c0-a998-6b3da3963bca,CAUF,[SWPS],تقليدية,متوسط,عن بعد,...,لا,البكالوريوس,علوم حاسب,1,0,3.72,4.0,خريج,مفقود,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,0,منطقة الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,[PCRF],تقليدية,مبتدئ,عن بعد,...,لا,البكالوريوس,تقنية المعلومات,1,0,2.00,4.0,موظف,مفقود,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,0,منطقة الرياض,03ec0d20-11cd-49bf-9b54-de5d12d4bd76,CAUF,[SWPS],مفقود,مفقود,عن بعد,...,نعم,البكالوريوس,شبكات الحاسب الآلي,1,0,3.72,5.0,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,0,منطقة الرياض,4ad7a7dc-abcf-43fa-b2e3-07095e083661,PCRF,[PCRF],مفقود,متقدم,حضوري,...,نعم,البكالوريوس,Biology,1,0,4.47,5.0,غير موظف,مفقود,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,0,منطقة الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,[TOSL],داعمة,متقدم,حضوري,...,نعم,الدبلوم,تقنية المعلومات,1,0,4.46,5.0,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,1,منطقة الرياض,1b546d80-2ed0-42e6-9867-61b3d2f92d50,GRST,[INFA],مفقود,متوسط,حضوري,...,نعم,البكالوريوس,علوم حاسب,1,0,2.55,5.0,موظف,مفقود,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,1,منطقة الرياض,aa87165d-cbde-4453-baca-1c8c03775e39,CAUF,[CRDP],داعمة,مبتدئ,حضوري,...,نعم,البكالوريوس,الهندسة الكهربائية,0,1,3.00,4.0,موظف,مفقود,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,1,منطقة الرياض,c49987af-b421-4b88-b36a-a0ec91d95aa3,GRST,[INFA],تقليدية,متوسط,حضوري,...,نعم,البكالوريوس,شبكات حاسب,1,0,3.00,5.0,موظف,مفقود,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,0,منطقة الرياض,899795e1-7bf3-46d0-a58e-824d4033f6da,PCRF,[PCRF],تقليدية,متوسط,عن بعد,...,لا,البكالوريوس,نظم معلومات,1,0,4.12,5.0,غير موظف,مفقود,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,1,منطقة الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,[PCRF],تقليدية,مبتدئ,حضوري,...,نعم,البكالوريوس,هندسة برمجيات,1,0,4.55,5.0,خريج,مفقود,91.0

In [161]:
df.drop(columns=['College_غير ذلك'], inplace=True)
df

,Student ID,Age,Gender_ذكر,Home Region,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,Program Presentation Method,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College_تكنولوجيا الاتصالات والمعلومات,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,0,منطقة الرياض,451d680f-e067-41c0-a998-6b3da3963bca,CAUF,[SWPS],تقليدية,متوسط,عن بعد,...,5,لا,البكالوريوس,علوم حاسب,1,3.72,4.0,خريج,مفقود,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,0,منطقة الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,[PCRF],تقليدية,مبتدئ,عن بعد,...,19,لا,البكالوريوس,تقنية المعلومات,1,2.00,4.0,موظف,مفقود,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,0,منطقة الرياض,03ec0d20-11cd-49bf-9b54-de5d12d4bd76,CAUF,[SWPS],مفقود,مفقود,عن بعد,...,12,نعم,البكالوريوس,شبكات الحاسب الآلي,1,3.72,5.0,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,0,منطقة الرياض,4ad7a7dc-abcf-43fa-b2e3-07095e083661,PCRF,[PCRF],مفقود,متقدم,حضوري,...,5,نعم,البكالوريوس,Biology,1,4.47,5.0,غير موظف,مفقود,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,0,منطقة الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,[TOSL],داعمة,متقدم,حضوري,...,33,نعم,الدبلوم,تقنية المعلومات,1,4.46,5.0,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,1,منطقة الرياض,1b546d80-2ed0-42e6-9867-61b3d2f92d50,GRST,[INFA],مفقود,متوسط,حضوري,...,5,نعم,البكالوريوس,علوم حاسب,1,2.55,5.0,موظف,مفقود,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,1,منطقة الرياض,aa87165d-cbde-4453-baca-1c8c03775e39,CAUF,[CRDP],داعمة,مبتدئ,حضوري,...,47,نعم,البكالوريوس,الهندسة الكهربائية,0,3.00,4.0,موظف,مفقود,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,1,منطقة الرياض,c49987af-b421-4b88-b36a-a0ec91d95aa3,GRST,[INFA],تقليدية,متوسط,حضوري,...,5,نعم,البكالوريوس,شبكات حاسب,1,3.00,5.0,موظف,مفقود,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,0,منطقة الرياض,899795e1-7bf3-46d0-a58e-824d4033f6da,PCRF,[PCRF],تقليدية,متوسط,عن بعد,...,173,لا,البكالوريوس,نظم معلومات,1,4.12,5.0,غير موظف,مفقود,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,1,منطقة الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,[PCRF],تقليدية,مبتدئ,حضوري,...,12,نعم,البكالوريوس,هندسة برمجيات,1,4.55,5.0,خريج,مفقود,91.0

In [162]:
encoder= ce.OneHotEncoder(cols='Home Region',return_df=True,use_cat_names=True)
df=encoder.fit_transform(df)
df

,Student ID,Age,Gender_ذكر,Home Region_منطقة الرياض,Home Region_المنطقة الشرقية,Home Region_منطقة مكة المكرمة,Home Region_منطقة عسير,Home Region_منطقة تبوك,Home Region_منطقة المدينة المنورة,Home Region_منطقة الحدود الشمالية,...,Program Days,Completed Degree,Level of Education,Education Speaciality,College_تكنولوجيا الاتصالات والمعلومات,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,0,1,0,0,0,0,0,0,...,5,لا,البكالوريوس,علوم حاسب,1,3.72,4.0,خريج,مفقود,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,0,1,0,0,0,0,0,0,...,19,لا,البكالوريوس,تقنية المعلومات,1,2.00,4.0,موظف,مفقود,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,0,1,0,0,0,0,0,0,...,12,نعم,البكالوريوس,شبكات الحاسب الآلي,1,3.72,5.0,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,0,1,0,0,0,0,0,0,...,5,نعم,البكالوريوس,Biology,1,4.47,5.0,غير موظف,مفقود,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,0,1,0,0,0,0,0,0,...,33,نعم,الدبلوم,تقنية المعلومات,1,4.46,5.0,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,1,1,0,0,0,0,0,0,...,5,نعم,البكالوريوس,علوم حاسب,1,2.55,5.0,موظف,مفقود,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,1,1,0,0,0,0,0,0,...,47,نعم,البكالوريوس,الهندسة الكهربائية,0,3.00,4.0,موظف,مفقود,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,1,1,0,0,0,0,0,0,...,5,نعم,البكالوريوس,شبكات حاسب,1,3.00,5.0,موظف,مفقود,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,0,1,0,0,0,0,0,0,...,173,لا,البكالوريوس,نظم معلومات,1,4.12,5.0,غير موظف,مفقود,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,1,1,0,0,0,0,0,0,...,12,نعم,البكالوريوس,هندسة برمجيات,1,4.55,5.0,خريج,مفقود,91.0

In [163]:
encoder= ce.OneHotEncoder(cols='Completed Degree',return_df=True,use_cat_names=True)
df=encoder.fit_transform(df)
df

,Student ID,Age,Gender_ذكر,Home Region_منطقة الرياض,Home Region_المنطقة الشرقية,Home Region_منطقة مكة المكرمة,Home Region_منطقة عسير,Home Region_منطقة تبوك,Home Region_منطقة المدينة المنورة,Home Region_منطقة الحدود الشمالية,...,Completed Degree_لا,Completed Degree_نعم,Level of Education,Education Speaciality,College_تكنولوجيا الاتصالات والمعلومات,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,0,1,0,0,0,0,0,0,...,1,0,البكالوريوس,علوم حاسب,1,3.72,4.0,خريج,مفقود,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,0,1,0,0,0,0,0,0,...,1,0,البكالوريوس,تقنية المعلومات,1,2.00,4.0,موظف,مفقود,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,0,1,0,0,0,0,0,0,...,0,1,البكالوريوس,شبكات الحاسب الآلي,1,3.72,5.0,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,0,1,0,0,0,0,0,0,...,0,1,البكالوريوس,Biology,1,4.47,5.0,غير موظف,مفقود,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,0,1,0,0,0,0,0,0,...,0,1,الدبلوم,تقنية المعلومات,1,4.46,5.0,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,1,1,0,0,0,0,0,0,...,0,1,البكالوريوس,علوم حاسب,1,2.55,5.0,موظف,مفقود,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,1,1,0,0,0,0,0,0,...,0,1,البكالوريوس,الهندسة الكهربائية,0,3.00,4.0,موظف,مفقود,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,1,1,0,0,0,0,0,0,...,0,1,البكالوريوس,شبكات حاسب,1,3.00,5.0,موظف,مفقود,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,0,1,0,0,0,0,0,0,...,1,0,البكالوريوس,نظم معلومات,1,4.12,5.0,غير موظف,مفقود,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,1,1,0,0,0,0,0,0,...,0,1,البكالوريوس,هندسة برمجيات,1,4.55,5.0,خريج,مفقود,91.0

In [164]:
df.drop(columns=['Completed Degree_لا'], inplace=True)
df

,Student ID,Age,Gender_ذكر,Home Region_منطقة الرياض,Home Region_المنطقة الشرقية,Home Region_منطقة مكة المكرمة,Home Region_منطقة عسير,Home Region_منطقة تبوك,Home Region_منطقة المدينة المنورة,Home Region_منطقة الحدود الشمالية,...,Program Days,Completed Degree_نعم,Level of Education,Education Speaciality,College_تكنولوجيا الاتصالات والمعلومات,University Degree Score,University Degree Score System,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,0,1,0,0,0,0,0,0,...,5,0,البكالوريوس,علوم حاسب,1,3.72,4.0,خريج,مفقود,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,0,1,0,0,0,0,0,0,...,19,0,البكالوريوس,تقنية المعلومات,1,2.00,4.0,موظف,مفقود,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,0,1,0,0,0,0,0,0,...,12,1,البكالوريوس,شبكات الحاسب الآلي,1,3.72,5.0,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,0,1,0,0,0,0,0,0,...,5,1,البكالوريوس,Biology,1,4.47,5.0,غير موظف,مفقود,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,0,1,0,0,0,0,0,0,...,33,1,الدبلوم,تقنية المعلومات,1,4.46,5.0,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,1,1,0,0,0,0,0,0,...,5,1,البكالوريوس,علوم حاسب,1,2.55,5.0,موظف,مفقود,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,1,1,0,0,0,0,0,0,...,47,1,البكالوريوس,الهندسة الكهربائية,0,3.00,4.0,موظف,مفقود,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,1,1,0,0,0,0,0,0,...,5,1,البكالوريوس,شبكات حاسب,1,3.00,5.0,موظف,مفقود,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,0,1,0,0,0,0,0,0,...,173,0,البكالوريوس,نظم معلومات,1,4.12,5.0,غير موظف,مفقود,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,1,1,0,0,0,0,0,0,...,12,1,البكالوريوس,هندسة برمجيات,1,4.55,5.0,خريج,مفقود,91.0

In [165]:
# Since Degree_Score_Pct is created, we don't need University Degree Score and University Degree Score System anymore
df.drop(columns=['University Degree Score'], inplace=True)
df.drop(columns=['University Degree Score System'], inplace=True)
df

,Student ID,Age,Gender_ذكر,Home Region_منطقة الرياض,Home Region_المنطقة الشرقية,Home Region_منطقة مكة المكرمة,Home Region_منطقة عسير,Home Region_منطقة تبوك,Home Region_منطقة المدينة المنورة,Home Region_منطقة الحدود الشمالية,...,Program Start Date,Program End Date,Program Days,Completed Degree_نعم,Level of Education,Education Speaciality,College_تكنولوجيا الاتصالات والمعلومات,Employment Status,Job Type,Degree_Score_Pct
0,d8524ed6-a1b2-4f6f-9041-66eebcab899a,23.0,0,1,0,0,0,0,0,0,...,2023-10-08,2023-10-12,5,0,البكالوريوس,علوم حاسب,1,خريج,مفقود,93.0
1,5490b973-d85e-4b26-93a8-ecc11c47a5a0,31.0,0,1,0,0,0,0,0,0,...,2023-07-16,2023-08-03,19,0,البكالوريوس,تقنية المعلومات,1,موظف,مفقود,50.0
2,3c1d99c8-f25b-4198-b904-aacb15164888,29.0,0,1,0,0,0,0,0,0,...,2022-12-25,2023-01-05,12,1,البكالوريوس,شبكات الحاسب الآلي,1,موظف,دوام كامل,74.4
3,9e57ee90-2d60-48b8-91a1-7caa49f03810,23.0,0,1,0,0,0,0,0,0,...,2023-03-19,2023-03-23,5,1,البكالوريوس,Biology,1,غير موظف,مفقود,89.4
4,a11b482b-6cc3-4e1a-8b95-60ab2e42097a,30.0,0,1,0,0,0,0,0,0,...,2023-11-12,2023-12-14,33,1,الدبلوم,تقنية المعلومات,1,غير موظف,دوام كامل,89.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,c4bd99a6-2902-4822-947e-2a3aab3f1e92,36.0,1,1,0,0,0,0,0,0,...,2023-08-13,2023-08-17,5,1,البكالوريوس,علوم حاسب,1,موظف,مفقود,51.0
814,2e057846-ee90-4b31-b6e7-c1c5122f4cbd,29.0,1,1,0,0,0,0,0,0,...,2023-11-26,2024-01-11,47,1,البكالوريوس,الهندسة الكهربائية,0,موظف,مفقود,75.0
815,8f9ff50d-510c-4d56-b0eb-60c2fb1c5e84,32.0,1,1,0,0,0,0,0,0,...,2023-07-23,2023-07-27,5,1,البكالوريوس,شبكات حاسب,1,موظف,مفقود,60.0
816,8a49b6cd-e7c3-460b-8126-a419cf995e6e,28.0,0,1,0,0,0,0,0,0,...,2023-05-14,2023-11-02,173,0,البكالوريوس,نظم معلومات,1,غير موظف,مفقود,82.4
817,4a15a037-f5f4-4947-8a67-9f28494a6f26,23.0,1,1,0,0,0,0,0,0,...,2023-07-16,2023-07-27,12,1,البكالوريوس,هندسة برمجيات,1,خريج,مفقود,91.0

In [166]:
df.to_pickle('Cleaned_test.pickle')