# Overview
Welcome to Tuwaiq Academy, a non-profit training institute in Saudi Arabia. With millions of applicants vying for limited seats in advanced AI programs, this challenge is your chance to revolutionize the allocation process. Your task is to build a predictive model that identifies top candidates likely to successfully complete the training program.

### Goal:
The goal of the competition is to develop an efficient model that sifts through the pool of applicants, pinpointing those with the highest likelihood of completing Tuwaiq Academy's rigorous training programs. By achieving this, you contribute to the strategic utilization of limited seats, ensuring they are granted to individuals your model identifies as having the best potential to excel in the program. Seize the challenge, make a lasting impact!

# Description
### Overview:
Tuwaiq Academy, a non-profit educational institute in the Kingdom of Saudi Arabia, is on a mission to advance AI and emerging technologies. With a surge in applications and limited seats for our coveted advanced programs, we invite you to participate in this competition for educational excellence.

### Objective:
In the face of millions of applicants, Tuwaiq Academy aims to streamline the selection process for our advanced training programs. Your challenge is to develop a predictive model that can accurately identify individuals with the highest likelihood of successfully completing the rigorous training curriculum.

### Why Participate:

* Impactful Contribution: Your efforts directly influence the strategic allocation of limited seats, ensuring they are granted to those most likely to excel in the program.
* Advancing Education: By participating in this competition, you become a key player in shaping the future of education, contributing to the growth of knowledge and expertise in the field.
### Key Details:

* Dataset: We provide registration information for accepted trainees in a variety of training programs, including a completion target column.
* Objective: Develop a robust model to identify candidates with the best potential for successful program completion.
* Outcome: The winning models will significantly enhance the efficiency of the selection process, allowing Tuwaiq Academy to optimize resource allocation and make a lasting impact on the education landscape.
### How to Win:

* Accuracy: Build a model that accurately predicts trainees' likelihood of completing the program.
* Innovation: Stand out by incorporating innovative approaches, algorithms, or features that elevate the predictive power of your model.
* Explanation: Provide insights into the factors driving your model's predictions, demonstrating a clear understanding of the problem.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Installing required Libraries:

In [145]:
import pandas as pd
import numpy as np

# Exploratory Data Analysis (EDA)

In [146]:
df=pd.read_csv('train.csv')
df

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working,Y
0,4f14c50d-162e-4a15-9cf0-ec129c33bcf0,37.0,ذكر,منطقة الرياض,الرياض,453686d8-4023-4506-b2df-fac8b059ac26,PCRF,PCRF,NaN,NaN,...,نعم,البكالوريوس,هندسة حاسب الالي,NaN,2.44,4.0,غير موظف,NaN,NaN,0
1,0599d409-876b-41a5-af05-749ef0e77d32,21.0,ذكر,منطقة عسير,خميس مشيط,cc8e4e42-65d5-4fa1-82f9-6c6c2d508b60,APMR,SWPS,NaN,متوسط,...,نعم,البكالوريوس,الإذاعة والتلفزيون والفيلم,الفنون والعلوم الإنسانية,5.00,5.0,طالب,NaN,NaN,0
2,38a11c0e-4afc-4261-9c64-e94cc0a272fb,24.0,ذكر,منطقة الرياض,الرياض,e006900d-05a9-4c2b-a36f-0ffb9fce44cd,APMR,NaN,NaN,متوسط,...,نعم,البكالوريوس,Information Technology,NaN,3.50,5.0,موظف,NaN,NaN,0
3,1693e85b-f80e-40ce-846f-395ddcece6d3,23.0,ذكر,منطقة الرياض,الرياض,2ec15f6b-233b-428a-b9f5-e40bc8d14cf9,TOSL,TOSL,NaN,NaN,...,نعم,البكالوريوس,حوسبة تطبيقية - (مسار شبكات الحاسب),NaN,3.55,5.0,خريج,NaN,NaN,0
4,98a0e8d0-5f80-4634-afd8-322aa0902863,23.0,ذكر,منطقة الرياض,الرياض,d32da0e9-1aed-48c3-992d-a22f9ccc741e,CAUF,SWPS,تقليدية,متوسط,...,لا,البكالوريوس,نظم المعلومات الحاسوبية,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6543,cd196579-9590-441b-8787-41078f3cee25,31.0,أنثى,منطقة الرياض,الرياض,4f8c696a-b783-4d40-9776-105f6d3bd624,CAUF,SWPS,NaN,NaN,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.40,5.0,NaN,NaN,NaN,0
6544,37bfc11c-ff8c-42dc-9cf9-0d13bb8f7131,27.0,أنثى,منطقة القصيم,بريدة,e94942dd-8684-4746-97ae-df567b9b0a4a,PCRF,PCRF,NaN,مبتدئ,...,نعم,البكالوريوس,علوم الحاسب,NaN,4.46,5.0,موظف,NaN,NaN,0
6545,fc114302-a79f-439f-a08b-fe0a51cf839e,24.0,أنثى,منطقة الرياض,الرياض,02ae0b47-64a6-47a1-b3c5-c0e4df393c30,PCRF,PCRF,تقليدية,مبتدئ,...,لا,البكالوريوس,نظم المعلومات,تكنولوجيا الاتصالات والمعلومات,4.93,5.0,موظف,دوام كامل,Yes,1
6546,4b6d9a36-4402-4c75-bc3a-fca927dbaf65,25.0,ذكر,منطقة الرياض,الرياض,9b4cedaa-fac0-4eac-aa4b-b05b6a0c97ff,PCRF,PCRF,NaN,متوسط,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.00,4.0,غير موظف,تدريب,No,0
6547,008f3386-0d43-45a4-8372-b282e5a0101a,37.0,أنثى,منطقة الرياض,الرياض,d8fbc53c-e042-4e45-b8c7-42b4ad0528ee,CAUF,NaN,NaN,مبتدئ,...,نعم,الماجستير,دراسات وقضايا معاصرة,NaN,4.32,5.0,موظف,NaN,NaN,0

In [147]:
df.shape

(6548, 24)

In [148]:
df.describe()

,Age,Program Days,University Degree Score,University Degree Score System,Y
count,6456.000000,6548.000000,6467.000000,6467.000000,6548.000000
mean,26.831165,19.691662,8.224432,9.773929,0.158674
std,5.535967,32.112061,19.120384,21.259962,0.365400
min,18.000000,3.000000,0.000000,4.000000,0.000000
25%,23.000000,5.000000,3.300000,5.000000,0.000000
50%,25.000000,12.000000,4.000000,5.000000,0.000000
75%,29.000000,19.000000,4.510000,5.000000,0.000000
max,57.000000,292.000000,100.000000,100.000000,1.000000

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6548 entries, 0 to 6547
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Student ID                      6548 non-null   object
 1   Age                             6456 non-null   float64
 2   Gender                          6548 non-null   object
 3   Home Region                     6546 non-null   object
 4   Home City                       6546 non-null   object
 5   Program ID                      6548 non-null   object
 6   Program Main Category Code      6548 non-null   object
 7   Program Sub Category Code       5613 non-null   object
 8   Technology Type                 3566 non-null   object
 9   Program Skill Level             4902 non-null   object
 10  Program Presentation Method     6548 non-null   object
 11  Program Start Date              6548 non-null   object
 12  Program End Date                6548 non-null   object
 13  Program Days                    6548 non-null   int64
 14  Completed Degree                6548 non-null   object
 15  Level of Education              6522 non-null   object
 16  Education Speaciality           6271 non-null   object
 17  College                         2658 non-null   object
 18  University Degree Score         6467 non-null   float64
 19  University Degree Score System  6467 non-null   float64
 20  Employment Status               5982 non-null   object
 21  Job Type                        1981 non-null   object
 22  Still Working                   1981 non-null   object
 23  Y                               6548 non-null   int64
dtypes: float64(3), int64(2), object(19)
memory usage: 1.2+ MB

## Removing Duplicates

In [150]:
for i in df.columns:
    print(df[i].value_counts())
    print("---------------------")
# The first ID have been recorded for 9 times, we will check if the data have dublicates or not.

Student ID
415cfcb1-8dfa-459d-b719-d942cc5e19e1    9
b1ae7dcd-2de0-4797-9331-4e00f7099d3e    6
cc92fa1e-494d-406f-8faf-9019d15ed5d0    6
4baf0168-b21d-4f18-b85c-170d1023cb1c    6
647325d0-ef30-457b-b41d-e00e110e06f2    6
                                       ..
621c5334-db96-460e-982c-5f7c385b31b1    1
fb35317b-1e3e-492b-8ac1-119cb60c567b    1
85ec0b08-cf03-47d2-a10e-5e9cccf534c3    1
3c34ef05-7a14-4ed2-a50a-910acaa97006    1
6b27cd77-23aa-438b-bd0b-7abdb40a717c    1
Name: count, Length: 5196, dtype: int64
---------------------
Age
23.0    892
24.0    760
25.0    552
22.0    548
26.0    460
27.0    395
21.0    314
29.0    297
28.0    291
30.0    230
20.0    225
31.0    216
32.0    199
34.0    153
33.0    136
35.0    112
37.0     95
19.0     95
38.0     86
36.0     73
39.0     68
41.0     56
42.0     49
40.0     42
44.0     26
43.0     24
18.0     17
45.0     10
46.0      8
49.0      6
48.0      6
47.0      4
55.0      3
50.0      3
52.0      1
51.0      1
56.0      1
53.0      1
57.0      1
Name: count, dtype: int64
---------------------
Gender
أنثى    3664
ذكر     2884
Name: count, dtype: int64
---------------------
Home Region
منطقة الرياض             4783
منطقة مكة المكرمة         598
المنطقة الشرقية           450
منطقة المدينة المنورة     177
منطقة عسير                172
منطقة القصيم              103
منطقة جازان                59
منطقة تبوك                 50
منطقة الباحة               47
منطقة حائل                 36
منطقة نجران                29
منطقة الحدود الشمالية      21
منطقة الجوف                21
Name: count, dtype: int64
---------------------
Home City
الرياض             4720
جدة                 362
المدينة المنورة     131
الدمام              119
أبها                109
                   ...
تيماء                 1
طبرجل                 1
طريف                  1
ظهران الجنوب          1
أملج                  1
Name: count, Length: 92, dtype: int64
---------------------
Program ID
ab263106-20a8-42aa-9626-278e62ae3a49    134
1c8a5fbd-9986-486f-9d9b-b50568f2589b    120
ee1206d8-ea7a-492e-af9d-24d6f4039e18    100
bfe7c8aa-789e-4239-8043-8e7554fa564a    100
eaa49c92-77da-4177-9970-0146981a1b50     92
                                       ...
aa87165d-cbde-4453-baca-1c8c03775e39     11
bdf6a9e2-9be7-4aaa-a117-d7fb3c90c53f     11
9ae32585-d67f-4af1-8a7b-8e378984bb5b     10
2e464e9f-e33a-474c-8702-0e3b8c653f3e      9
e0fd5e0e-5d24-413b-96c8-be0525cfc2fa      8
Name: count, Length: 223, dtype: int64
---------------------
Program Main Category Code
CAUF    2358
PCRF    1682
APMR    1299
TOSL     500
GRST     208
ABIR     205
INFA     179
SERU      53
DTFH      33
QWLM      31
Name: count, dtype: int64
---------------------
Program Sub Category Code
SWPS    1788
PCRF    1682
SRTA     700
INFA     510
TOSL     295
CRDP     243
ERST     172
KLTM     117
QTDY      51
ASCW      36
ABIR      19
Name: count, dtype: int64
---------------------
Technology Type
تقليدية    2693
ناشئة       441
داعمة       432
Name: count, dtype: int64
---------------------
Program Skill Level
متوسط    2134
مبتدئ    2060
متقدم     708
Name: count, dtype: int64
---------------------
Program Presentation Method
حضوري     4964
عن بعد    1584
Name: count, dtype: int64
---------------------
Program Start Date
2023-04-02    345
2023-07-23    298
2023-07-16    267
2023-05-14    265
2023-03-05    246
             ...
2023-12-17     16
2022-09-18     16
2022-08-28     16
2022-09-21     15
2024-01-15     15
Name: count, Length: 77, dtype: int64
---------------------
Program End Date
2023-03-02    326
2023-04-06    324
2023-03-16    270
2023-09-14    263
2023-06-22    225
             ...
2023-01-20     15
2022-09-25     15
2022-12-07     13
2022-12-15      9
2023-12-07      8
Name: count, Length: 88, dtype: int64
---------------------
Program Days
5      2902
12     1566
54      531
19      374
26      311
33      125
4       113
40       99
173      80
44       77
59       60
3        37
9        35
10       32
80       28
292      25
47       22
66       21
25       19
248      18
21       18
96       17
135      15
20       15
61        8
Name: count, dtype: int64
---------------------
Completed Degree
نعم    5206
لا     1342
Name: count, dtype: int64
---------------------
Level of Education
البكالوريوس    5429
الماجستير       485
الدبلوم         310
ثانوي           268
الدكتوراه        30
Name: count, dtype: int64
---------------------
Education Speaciality
علوم الحاسبات                    1067
تقنية المعلومات                   712
نظم المعلومات                     457
علوم حاسب                         349
علوم الحاسب                       194
                                 ...
تقنية وادارة المعلومات الصحية       1
ادارة أنظمة شبكات                   1
علوم حاسبات - هندسة برمجيات         1
تصميم مواقع                         1
حاسب الي وسكرتارية                  1
Name: count, Length: 871, dtype: int64
---------------------
College
تكنولوجيا الاتصالات والمعلومات         2312
الأعمال والإدارة والقانون               153
العلوم الطبيعية والرياضيات والإحصاء      62
الهندسة والتصنيع والبناء                 43
الفنون والعلوم الإنسانية                 38
العلوم الاجتماعية والصحافة والإعلام      25
التعليم                                  19
الصحة والرفاة                             4
البرامج والمؤهلات العامة                  2
Name: count, dtype: int64
---------------------
University Degree Score
4.000     844
3.000     583
5.000     207
2.000     136
4.500     109
         ...
2.190       1
95.150      1
94.960      1
3.498       1
1.800       1
Name: count, Length: 435, dtype: int64
---------------------
University Degree Score System
5.0      4700
4.0      1427
100.0     340
Name: count, dtype: int64
---------------------
Employment Status
موظف           2801
غير موظف       1116
طالب            957
خريج            952
موظف - طالب      88
عمل حر           68
Name: count, dtype: int64
---------------------
Job Type
دوام كامل    1398
تدريب         478
دوام جزئي      61
تطوع           44
Name: count, dtype: int64
---------------------
Still Working
Yes    1246
No      735
Name: count, dtype: int64
---------------------
Y
0    5509
1    1039
Name: count, dtype: int64
---------------------

In [151]:
df.loc[df['Student ID'] == '415cfcb1-8dfa-459d-b719-d942cc5e19e1']
# the same student showed in the dataset but the other information is different, this means the student is signed 9 times for different programs(data is not duplicated)

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working,Y
418,415cfcb1-8dfa-459d-b719-d942cc5e19e1,44.0,ذكر,منطقة الرياض,الرياض,d0f06377-196d-486c-bad8-15c04f8cdad3,PCRF,PCRF,ناشئة,مبتدئ,...,نعم,الدبلوم,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,4.0,5.0,موظف,دوام كامل,Yes,0
785,415cfcb1-8dfa-459d-b719-d942cc5e19e1,44.0,ذكر,منطقة الرياض,الرياض,f2374bcb-111c-402d-beaf-37433687db4d,TOSL,NaN,NaN,مبتدئ,...,نعم,الدبلوم,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,4.0,5.0,موظف,دوام كامل,Yes,0
1700,415cfcb1-8dfa-459d-b719-d942cc5e19e1,44.0,ذكر,منطقة الرياض,الرياض,d8fbc53c-e042-4e45-b8c7-42b4ad0528ee,CAUF,NaN,NaN,مبتدئ,...,نعم,الدبلوم,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,4.0,5.0,موظف,دوام كامل,Yes,0
2302,415cfcb1-8dfa-459d-b719-d942cc5e19e1,44.0,ذكر,منطقة الرياض,الرياض,642f04b2-67f8-4403-98f1-c5c5755eb358,CAUF,SWPS,داعمة,متوسط,...,نعم,الدبلوم,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,4.0,5.0,موظف,دوام كامل,Yes,0
2818,415cfcb1-8dfa-459d-b719-d942cc5e19e1,44.0,ذكر,منطقة الرياض,الرياض,b3c56c6d-dd46-4f26-93ee-c16e211aa3b9,PCRF,PCRF,داعمة,مبتدئ,...,نعم,الدبلوم,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,4.0,5.0,موظف,دوام كامل,Yes,0
2969,415cfcb1-8dfa-459d-b719-d942cc5e19e1,44.0,ذكر,منطقة الرياض,الرياض,5b4d389b-ce84-46c4-87f0-70531fdaf1e7,INFA,INFA,NaN,NaN,...,نعم,الدبلوم,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,4.0,5.0,موظف,دوام كامل,Yes,0
4270,415cfcb1-8dfa-459d-b719-d942cc5e19e1,44.0,ذكر,منطقة الرياض,الرياض,1a3faefb-3708-40ab-82e6-4fcf07983665,PCRF,PCRF,داعمة,مبتدئ,...,نعم,الدبلوم,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,4.0,5.0,موظف,دوام كامل,Yes,0
4861,415cfcb1-8dfa-459d-b719-d942cc5e19e1,44.0,ذكر,منطقة الرياض,الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,PCRF,تقليدية,مبتدئ,...,نعم,الدبلوم,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,4.0,5.0,موظف,دوام كامل,Yes,0
5705,415cfcb1-8dfa-459d-b719-d942cc5e19e1,44.0,ذكر,منطقة الرياض,الرياض,9144fab5-59f3-4b98-bc3c-0784a04883fe,TOSL,TOSL,NaN,NaN,...,نعم,الدبلوم,شبكات الحاسب الآلي,تكنولوجيا الاتصالات والمعلومات,4.0,5.0,موظف,دوام كامل,Yes,0

In [152]:
df.duplicated().sum()
# Data shows that there is Identical rows, so we will need to delete the duplicates

np.int64(48)

In [153]:
# print the rows with duplicate information (sorted) to check that there is a true duplication
duplicated = df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())
duplicated

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working,Y
1475,023f77b4-1136-4049-890c-2ad8128db5ba,24.0,ذكر,منطقة الرياض,الرياض,21c233a1-0101-44e6-8af8-39d545bddaaf,PCRF,PCRF,NaN,NaN,...,نعم,البكالوريوس,علوم الحاسبات,تكنولوجيا الاتصالات والمعلومات,3.00,4.0,موظف,دوام كامل,Yes,0
3740,023f77b4-1136-4049-890c-2ad8128db5ba,24.0,ذكر,منطقة الرياض,الرياض,21c233a1-0101-44e6-8af8-39d545bddaaf,PCRF,PCRF,NaN,NaN,...,نعم,البكالوريوس,علوم الحاسبات,تكنولوجيا الاتصالات والمعلومات,3.00,4.0,موظف,دوام كامل,Yes,0
5319,1acd4e67-2970-4cc2-bcd0-ed1326379e40,35.0,ذكر,منطقة الرياض,الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,PCRF,تقليدية,مبتدئ,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.00,4.0,موظف,دوام كامل,Yes,0
6052,1acd4e67-2970-4cc2-bcd0-ed1326379e40,35.0,ذكر,منطقة الرياض,الرياض,0d6336e2-4a79-4c32-8f15-073f9a4f6976,PCRF,PCRF,تقليدية,مبتدئ,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.00,4.0,موظف,دوام كامل,Yes,0
3780,206447b4-433d-4950-b445-7e60e75b6ca8,40.0,ذكر,المنطقة الشرقية,الأحساء,1f09a274-8f35-41a1-9a5e-61a5f1cb98fc,TOSL,NaN,NaN,متوسط,...,نعم,البكالوريوس,علوم الحاسبات,تكنولوجيا الاتصالات والمعلومات,3.12,4.0,غير موظف,دوام كامل,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4189,ecbedd25-274c-439e-a31f-bbd7ac009714,32.0,ذكر,منطقة الرياض,الرياض,ab263106-20a8-42aa-9626-278e62ae3a49,CAUF,SWPS,تقليدية,متقدم,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,5.00,5.0,موظف,دوام كامل,Yes,0
2152,f2a20174-e002-45bf-a4a8-63be34062a60,24.0,ذكر,منطقة الباحة,الباحة,1f09a274-8f35-41a1-9a5e-61a5f1cb98fc,TOSL,NaN,NaN,متوسط,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.51,4.0,موظف,تدريب,Yes,0
2609,f2a20174-e002-45bf-a4a8-63be34062a60,24.0,ذكر,منطقة الباحة,الباحة,1f09a274-8f35-41a1-9a5e-61a5f1cb98fc,TOSL,NaN,NaN,متوسط,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,2.51,4.0,موظف,تدريب,Yes,0
2507,fabd4c95-3908-4dd9-b28d-8a6f05629880,23.0,أنثى,منطقة الرياض,الرياض,1f09a274-8f35-41a1-9a5e-61a5f1cb98fc,TOSL,NaN,NaN,متوسط,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,NaN,NaN,NaN,0
4434,fabd4c95-3908-4dd9-b28d-8a6f05629880,23.0,أنثى,منطقة الرياض,الرياض,1f09a274-8f35-41a1-9a5e-61a5f1cb98fc,TOSL,NaN,NaN,متوسط,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,NaN,NaN,NaN,0

In [154]:
# removing duplicates
df.drop_duplicates(inplace=True)

df.shape

(6500, 24)

## Changing date format

In [155]:
df['Program Start Date']=pd.to_datetime(df['Program Start Date'])
df['Program End Date']=pd.to_datetime(df['Program End Date'])

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6500 entries, 0 to 6547
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Student ID                      6500 non-null   object
 1   Age                             6413 non-null   float64
 2   Gender                          6500 non-null   object
 3   Home Region                     6498 non-null   object
 4   Home City                       6498 non-null   object
 5   Program ID                      6500 non-null   object
 6   Program Main Category Code      6500 non-null   object
 7   Program Sub Category Code       5580 non-null   object
 8   Technology Type                 3542 non-null   object
 9   Program Skill Level             4855 non-null   object
 10  Program Presentation Method     6500 non-null   object
 11  Program Start Date              6500 non-null   datetime64[ns]
 12  Program End Date                6500 non-null   datetime64[ns]
 13  Program Days                    6500 non-null   int64
 14  Completed Degree                6500 non-null   object
 15  Level of Education              6478 non-null   object
 16  Education Speaciality           6228 non-null   object
 17  College                         2638 non-null   object
 18  University Degree Score         6424 non-null   float64
 19  University Degree Score System  6424 non-null   float64
 20  Employment Status               5943 non-null   object
 21  Job Type                        1965 non-null   object
 22  Still Working                   1965 non-null   object
 23  Y                               6500 non-null   int64
dtypes: datetime64[ns](2), float64(3), int64(2), object(17)
memory usage: 1.2+ MB

## Fixing Nulls

In [157]:
df.isna().sum()

Student ID                           0
Age                                 87
Gender                               0
Home Region                          2
Home City                            2
Program ID                           0
Program Main Category Code           0
Program Sub Category Code          920
Technology Type                   2958
Program Skill Level               1645
Program Presentation Method          0
Program Start Date                   0
Program End Date                     0
Program Days                         0
Completed Degree                     0
Level of Education                  22
Education Speaciality              272
College                           3862
University Degree Score             76
University Degree Score System      76
Employment Status                  557
Job Type                          4535
Still Working                     4535
Y                                    0
dtype: int64

In [158]:
# Age:
df['Age'].value_counts()

Age
23.0    886
24.0    750
25.0    549
22.0    546
26.0    459
27.0    392
21.0    314
29.0    296
28.0    288
30.0    230
20.0    225
31.0    216
32.0    194
34.0    152
33.0    136
35.0    111
19.0     95
37.0     93
38.0     84
36.0     72
39.0     67
41.0     56
42.0     49
40.0     41
44.0     26
43.0     24
18.0     17
45.0     10
46.0      8
49.0      6
48.0      6
47.0      4
55.0      3
50.0      3
52.0      1
51.0      1
56.0      1
53.0      1
57.0      1
Name: count, dtype: int64

In [159]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Age'].value_counts()

C:\Users\Admin\AppData\Local\Temp\ipykernel_3996\514352096.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

Age
23.0    886
24.0    750
25.0    636
22.0    546
26.0    459
27.0    392
21.0    314
29.0    296
28.0    288
30.0    230
20.0    225
31.0    216
32.0    194
34.0    152
33.0    136
35.0    111
19.0     95
37.0     93
38.0     84
36.0     72
39.0     67
41.0     56
42.0     49
40.0     41
44.0     26
43.0     24
18.0     17
45.0     10
46.0      8
49.0      6
48.0      6
47.0      4
55.0      3
50.0      3
52.0      1
51.0      1
56.0      1
53.0      1
57.0      1
Name: count, dtype: int64

In [160]:
# Level of Education
df['Level of Education'].value_counts()

Level of Education
البكالوريوس    5391
الماجستير       481
الدبلوم         309
ثانوي           267
الدكتوراه        30
Name: count, dtype: int64

In [161]:
df['Level of Education'].fillna(df['Level of Education'].mode().iloc[0], inplace=True)
df['Level of Education'].value_counts()

C:\Users\Admin\AppData\Local\Temp\ipykernel_3996\2953953701.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Level of Education'].fillna(df['Level of Education'].mode().iloc[0], inplace=True)

Level of Education
البكالوريوس    5413
الماجستير       481
الدبلوم         309
ثانوي           267
الدكتوراه        30
Name: count, dtype: int64

In [162]:
df.head()

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working,Y
0,4f14c50d-162e-4a15-9cf0-ec129c33bcf0,37.0,ذكر,منطقة الرياض,الرياض,453686d8-4023-4506-b2df-fac8b059ac26,PCRF,PCRF,NaN,NaN,...,نعم,البكالوريوس,هندسة حاسب الالي,NaN,2.44,4.0,غير موظف,NaN,NaN,0
1,0599d409-876b-41a5-af05-749ef0e77d32,21.0,ذكر,منطقة عسير,خميس مشيط,cc8e4e42-65d5-4fa1-82f9-6c6c2d508b60,APMR,SWPS,NaN,متوسط,...,نعم,البكالوريوس,الإذاعة والتلفزيون والفيلم,الفنون والعلوم الإنسانية,5.00,5.0,طالب,NaN,NaN,0
2,38a11c0e-4afc-4261-9c64-e94cc0a272fb,24.0,ذكر,منطقة الرياض,الرياض,e006900d-05a9-4c2b-a36f-0ffb9fce44cd,APMR,NaN,NaN,متوسط,...,نعم,البكالوريوس,Information Technology,NaN,3.50,5.0,موظف,NaN,NaN,0
3,1693e85b-f80e-40ce-846f-395ddcece6d3,23.0,ذكر,منطقة الرياض,الرياض,2ec15f6b-233b-428a-b9f5-e40bc8d14cf9,TOSL,TOSL,NaN,NaN,...,نعم,البكالوريوس,حوسبة تطبيقية - (مسار شبكات الحاسب),NaN,3.55,5.0,خريج,NaN,NaN,0
4,98a0e8d0-5f80-4634-afd8-322aa0902863,23.0,ذكر,منطقة الرياض,الرياض,d32da0e9-1aed-48c3-992d-a22f9ccc741e,CAUF,SWPS,تقليدية,متوسط,...,لا,البكالوريوس,نظم المعلومات الحاسوبية,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,NaN,NaN,NaN,0

In [163]:
# Sub Category
main_sub_categories = df.groupby('Program Main Category Code')['Program Sub Category Code']\
                       .apply(lambda x: x.astype(str).unique())
print(main_sub_categories)

Program Main Category Code
ABIR                      [INFA, nan, ABIR]
APMR    [SWPS, nan, SRTA, KLTM, ASCW, QTDY]
CAUF                [SWPS, CRDP, nan, ERST]
DTFH                                  [nan]
GRST                                 [INFA]
INFA                                 [INFA]
PCRF                                 [PCRF]
QWLM                                  [nan]
SERU                           [INFA, ERST]
TOSL                            [TOSL, nan]
Name: Program Sub Category Code, dtype: object

In [164]:
def fill_sub_category(row):
    main_category = row['Program Main Category Code']
    sub_categories = row['Program Sub Category Code']

    # Handle case where sub_categories is a single NaN float
    if pd.isna(sub_categories):
        return [main_category]

    # Ensure sub_categories is always treated as a list
    if not isinstance(sub_categories, list):
        sub_categories = [sub_categories]

    # If all values are nan, fill with main category
    if all(pd.isna(x) for x in sub_categories):
        return [main_category] * len(sub_categories)

    # Replace nan values with first non-nan value if exists, otherwise main category
    first_non_nan = next((x for x in sub_categories if not pd.isna(x)), main_category)
    return [first_non_nan if pd.isna(x) else x for x in sub_categories]

# Apply the function to fill nan values
df['Program Sub Category Code'] = df.apply(fill_sub_category, axis=1)

In [165]:
main_sub_categories = df.groupby('Program Main Category Code')['Program Sub Category Code']\
                       .apply(lambda x: x.astype(str).unique())
print(main_sub_categories)

Program Main Category Code
ABIR                                 [['INFA'], ['ABIR']]
APMR    [['SWPS'], ['APMR'], ['SRTA'], ['KLTM'], ['ASC...
CAUF             [['SWPS'], ['CRDP'], ['CAUF'], ['ERST']]
DTFH                                           [['DTFH']]
GRST                                           [['INFA']]
INFA                                           [['INFA']]
PCRF                                           [['PCRF']]
QWLM                                           [['QWLM']]
SERU                                 [['INFA'], ['ERST']]
TOSL                                           [['TOSL']]
Name: Program Sub Category Code, dtype: object

In [166]:
df.isnull().sum()

Student ID                           0
Age                                  0
Gender                               0
Home Region                          2
Home City                            2
Program ID                           0
Program Main Category Code           0
Program Sub Category Code            0
Technology Type                   2958
Program Skill Level               1645
Program Presentation Method          0
Program Start Date                   0
Program End Date                     0
Program Days                         0
Completed Degree                     0
Level of Education                   0
Education Speaciality              272
College                           3862
University Degree Score             76
University Degree Score System      76
Employment Status                  557
Job Type                          4535
Still Working                     4535
Y                                    0
dtype: int64

In [167]:
# Home Region, Home City
# There is only 2 null records in Home Region, and they are also nulls in Home City thought, we will drop them
df[df['Home Region'].isnull()]

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Still Working,Y
1864,cc394a25-74ed-43f9-92bc-e0021fc969c5,45.0,ذكر,NaN,NaN,ce3562c8-8d27-4ffb-8dfc-e1dd4527b32a,PCRF,[PCRF],تقليدية,مبتدئ,...,نعم,الماجستير,نظم المعلومات الإدارية,الأعمال والإدارة والقانون,4.0,5.0,موظف,دوام كامل,Yes,0
3292,55b23798-369d-4698-8cb9-f8d1684bf1f8,25.0,ذكر,NaN,NaN,899795e1-7bf3-46d0-a58e-824d4033f6da,PCRF,[PCRF],تقليدية,متوسط,...,نعم,البكالوريوس,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [168]:
df.dropna(subset=['Home Region'], inplace=True)

In [ ]:
# Education Speaciality
# Since Tuwaiq academy provides a Program related to Computer Science,
# it is normal to have students who have Computer Science background to apply for, so we will fill the nulls with علوم الحاسبات
df['Education Speaciality'].value_counts()

Education Speaciality
علوم الحاسبات                    1061
تقنية المعلومات                   705
نظم المعلومات                     453
علوم حاسب                         346
علوم الحاسب                       193
                                 ...
Electrical engineer                 1
اداراة اعمال                        1
تقنية وادارة المعلومات الصحية       1
ادارة أنظمة شبكات                   1
علوم حاسبات - هندسة برمجيات         1
Name: count, Length: 871, dtype: int64

In [170]:
df['Education Speaciality'].fillna('علوم الحاسبات',inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_3996\4096565206.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Education Speaciality'].fillna('علوم الحاسبات',inplace=True)

In [171]:
# نوحد مسميات التخصصات
import re
import pandas as pd

def normalize_specialty(s):
    if pd.isna(s):
        return s
    s = str(s).strip().lower()

    # --- Computer Science & IT ---
    # علوم حاسب (Computer Science)
    if re.search(r'علوم\s*حاس(ب|بات|وب|ب\s*آلي|ب\s*الآلي|ب\.|ب$)', s) or \
       re.search(r'computer\s*science|cs|computing|علوم\s*الحاسب', s):
        return 'علوم حاسب'

    # هندسة حاسب (Computer Engineering)
    if re.search(r'هندسة\s*حاس(ب|بات|وب|ب\s*آلي|ب\s*الآلي|ب\.)', s) or \
       re.search(r'computer\s*engineering|هندسة\s*الحاسب', s):
        return 'هندسة حاسب'

    # تقنية معلومات (IT)
    if re.search(r'تقن(ية|يه)\s*معلومات|تكنولوجيا\s*معلومات|information\s*technology|it\b', s):
        return 'تقنية معلومات'

    # نظم معلومات (Information Systems)
    if re.search(r'نظم\s*معلومات|information\s*system|is\b|mis\b', s):
        return 'نظم معلومات'

    # أمن سيبراني (Cybersecurity)
    if re.search(r'أمن\s*سيبراني|cyber\s*security|cybersecurity|الأمن\s*السيبراني', s):
        return 'أمن سيبراني'

    # هندسة برمجيات (Software Engineering)
    if re.search(r'هندسة\s*برمجيات|software\s*engineering', s):
        return 'هندسة برمجيات'

    # --- Engineering ---
    # هندسة كهربائية (Electrical Engineering)
    if re.search(r'هندسة\s*كهربائية|electrical\s*engineering', s):
        return 'هندسة كهربائية'

    # --- Business ---
    # إدارة أعمال (Business Administration)
    if re.search(r'إدارة\s*أعمال|ادارة\s*اعمال|business\s*administration|mba', s):
        return 'إدارة أعمال'

    # --- Miscellaneous ---
    # غير متخصص (Non-Specialized)
    if re.search(r'غير\s*متخصص|non\-specialized|لا\s*يوجد', s):
        return 'غير متخصص'

    # Default: Return original string (title-cased)
    return s.title()

# Apply to DataFrame

df['Education Speaciality'] = df['Education Speaciality'].apply(normalize_specialty)

In [172]:
df['Education Speaciality'].value_counts()

Education Speaciality
علوم حاسب                            2297
تقنية المعلومات                       705
نظم المعلومات                         453
نظم معلومات                           450
تقنية معلومات                         305
                                     ...
Beng Computer Systems Engineering       1
نحت، فنون بصرية                         1
Public Administration                   1
Information Science                     1
Electrical Engineer                     1
Name: count, Length: 594, dtype: int64

In [ ]:
# College
# Since the data is about Tuwaiq academy, witch provides a computer science related courses, we will change the data into تكنولوجيا الاتصالات والمعلومات and غير ذلك,
# and fill the missing data with تكنولوجيا الاتصالات والمعلومات
df['College'].value_counts()

College
تكنولوجيا الاتصالات والمعلومات         2293
الأعمال والإدارة والقانون               151
العلوم الطبيعية والرياضيات والإحصاء      62
الهندسة والتصنيع والبناء                 43
الفنون والعلوم الإنسانية                 38
العلوم الاجتماعية والصحافة والإعلام      25
التعليم                                  19
الصحة والرفاة                             4
البرامج والمؤهلات العامة                  2
Name: count, dtype: int64

In [174]:
df['College'].fillna('تكنولوجيا الاتصالات والمعلومات', inplace=True)

df['College'] = df['College'].mask(
    df['College'] != 'تكنولوجيا الاتصالات والمعلومات',
    'غير ذلك'
)

df['College'].value_counts()

C:\Users\Admin\AppData\Local\Temp\ipykernel_3996\3326926096.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['College'].fillna('تكنولوجيا الاتصالات والمعلومات', inplace=True)

College
تكنولوجيا الاتصالات والمعلومات    6154
غير ذلك                            344
Name: count, dtype: int64

In [175]:
df['Employment Status'] = df['Employment Status'].fillna(df['Employment Status'].mode()[0])

In [176]:
# ما نحتاجه لانه موجود Employment Status
df = df.drop('Still Working', axis=1)

In [177]:
df['University Degree Score'] = df['University Degree Score'].fillna(df['University Degree Score'].median())
df['University Degree Score System'] = df['University Degree Score System'].fillna(df['University Degree Score System'].mode()[0])

In [178]:
df.isna().sum()

Student ID                           0
Age                                  0
Gender                               0
Home Region                          0
Home City                            0
Program ID                           0
Program Main Category Code           0
Program Sub Category Code            0
Technology Type                   2958
Program Skill Level               1645
Program Presentation Method          0
Program Start Date                   0
Program End Date                     0
Program Days                         0
Completed Degree                     0
Level of Education                   0
Education Speaciality                0
College                              0
University Degree Score              0
University Degree Score System       0
Employment Status                    0
Job Type                          4534
Y                                    0
dtype: int64

In [180]:
mode_count =(df['Program Skill Level'] == 'متوسط').sum()
mode_count

np.int64(2104)

In [181]:
df['Program Skill Level'].value_counts()

Program Skill Level
متوسط    2104
مبتدئ    2052
متقدم     697
Name: count, dtype: int64

In [182]:
#normalized score system
#عشان تكون المعدلات ادق
df['Degree_Score_Normalized'] = (
    df['University Degree Score'] 
    / df['University Degree Score System']
)

df['Degree_Score_Pct'] = df['Degree_Score_Normalized'] * 100
df.drop(columns=['Degree_Score_Normalized'], inplace=True)

In [183]:
df['Program ID'].value_counts()

Program ID
ab263106-20a8-42aa-9626-278e62ae3a49    133
1c8a5fbd-9986-486f-9d9b-b50568f2589b    111
ee1206d8-ea7a-492e-af9d-24d6f4039e18    100
bfe7c8aa-789e-4239-8043-8e7554fa564a    100
eaa49c92-77da-4177-9970-0146981a1b50     91
                                       ...
aa87165d-cbde-4453-baca-1c8c03775e39     11
bdf6a9e2-9be7-4aaa-a117-d7fb3c90c53f     11
9ae32585-d67f-4af1-8a7b-8e378984bb5b     10
2e464e9f-e33a-474c-8702-0e3b8c653f3e      9
e0fd5e0e-5d24-413b-96c8-be0525cfc2fa      8
Name: count, Length: 223, dtype: int64

In [184]:
df['Completed Degree'].value_counts()

Completed Degree
نعم    5158
لا     1340
Name: count, dtype: int64

In [185]:
df['Technology Type'].value_counts()

Technology Type
تقليدية    2668
ناشئة       440
داعمة       432
Name: count, dtype: int64

In [186]:
df['Technology Type'].isna().sum()

np.int64(2958)

In [ ]:
#we will filled the missing data in Technology Type with مفقود since its nearly half of the data
df['Technology Type'] = df['Technology Type'].fillna('مفقود')

In [188]:
#only where the Y is 1
#it shows only 1039 rows 
df_y_is1 = df[df['Y']==1]
df_y_is1

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Y,Degree_Score_Pct
9,621c5334-db96-460e-982c-5f7c385b31b1,20.0,ذكر,منطقة نجران,نجران,04df155c-2eef-496e-b38e-30283b56249c,PCRF,[PCRF],تقليدية,مبتدئ,...,لا,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,2.00,5.0,موظف - طالب,دوام كامل,1,40.0
12,314850c4-036b-4773-a3c8-f34694ff79f2,29.0,ذكر,منطقة الرياض,الرياض,9a48a693-5c44-4c91-9443-417178621789,PCRF,[PCRF],مفقود,NaN,...,لا,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,3.00,4.0,موظف,NaN,1,75.0
25,ad9a759e-710f-48c7-a055-8c4b7fb531a4,26.0,أنثى,منطقة الرياض,الرياض,2d5681bc-aa1c-4d85-bd5e-58f14bb9c317,INFA,[INFA],مفقود,NaN,...,لا,البكالوريوس,نظم معلومات,تكنولوجيا الاتصالات والمعلومات,4.10,5.0,عمل حر,NaN,1,82.0
36,5e5c78ed-8517-4c7e-9df8-47af9cf24adf,20.0,أنثى,منطقة الرياض,الرياض,84878a26-c398-48e9-a5b2-2c6d8efaa550,CAUF,[SWPS],مفقود,NaN,...,لا,البكالوريوس,تصميم منتجات,تكنولوجيا الاتصالات والمعلومات,4.45,5.0,طالب,NaN,1,89.0
39,5f57c7ff-a041-45a7-84c0-517d563eb514,23.0,أنثى,منطقة المدينة المنورة,المدينة المنورة,dd948935-4e37-4454-81f2-13d75c10cd69,PCRF,[PCRF],مفقود,NaN,...,لا,الدكتوراه,تاريخ اسلامي,تكنولوجيا الاتصالات والمعلومات,4.84,5.0,خريج,NaN,1,96.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6532,10c6c83c-50a4-454d-96b1-b7274bc12435,29.0,أنثى,منطقة مكة المكرمة,جدة,f525fd4a-d0bd-4278-b69b-1824604d6092,SERU,[ERST],تقليدية,متوسط,...,لا,البكالوريوس,الأحياء,غير ذلك,2.00,4.0,غير موظف,دوام كامل,1,50.0
6534,7cebba8b-26eb-4f2c-b6d0-abf5acb19bf7,35.0,أنثى,منطقة الرياض,الرياض,0d12d5ef-7965-4a0d-a18c-7cc826c4f971,APMR,[SRTA],داعمة,مبتدئ,...,لا,الماجستير,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,موظف,NaN,1,80.0
6536,1454b136-fe45-4b34-8b04-2af85635b626,21.0,ذكر,منطقة نجران,نجران,dd948935-4e37-4454-81f2-13d75c10cd69,PCRF,[PCRF],مفقود,NaN,...,لا,الدبلوم,دعم فني,تكنولوجيا الاتصالات والمعلومات,4.96,5.0,طالب,NaN,1,99.2
6537,dacd9f4d-9179-4649-8b54-6ef8104e3d46,24.0,ذكر,منطقة الرياض,الرياض,c2e3fed5-4898-4b06-b141-fdd3cfb8db9a,CAUF,[CRDP],مفقود,NaN,...,لا,البكالوريوس,الشريعة,تكنولوجيا الاتصالات والمعلومات,4.42,5.0,موظف,NaN,1,88.4
6545,fc114302-a79f-439f-a08b-fe0a51cf839e,24.0,أنثى,منطقة الرياض,الرياض,02ae0b47-64a6-47a1-b3c5-c0e4df393c30,PCRF,[PCRF],تقليدية,مبتدئ,...,لا,البكالوريوس,نظم المعلومات,تكنولوجيا الاتصالات والمعلومات,4.93,5.0,موظف,دوام كامل,1,98.6

In [189]:
complete = df_y_is1.groupby('Technology Type').size().reset_index(name='count')
complete

  Technology Type  count
0         تقليدية    481
1           داعمة     77
2           مفقود    423
3           ناشئة     58

In [190]:
df['Program Skill Level'].isna().sum()

np.int64(1645)

In [ ]:
##we will filled the missing data in Program Skill Level with مفقود
#we made all the nulls to مفقود because nulls doesnt apear while training and testing

df['Program Skill Level'] = df['Program Skill Level'].fillna('مفقود')
df

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Y,Degree_Score_Pct
0,4f14c50d-162e-4a15-9cf0-ec129c33bcf0,37.0,ذكر,منطقة الرياض,الرياض,453686d8-4023-4506-b2df-fac8b059ac26,PCRF,[PCRF],مفقود,مفقود,...,نعم,البكالوريوس,هندسة حاسب,تكنولوجيا الاتصالات والمعلومات,2.44,4.0,غير موظف,NaN,0,61.0
1,0599d409-876b-41a5-af05-749ef0e77d32,21.0,ذكر,منطقة عسير,خميس مشيط,cc8e4e42-65d5-4fa1-82f9-6c6c2d508b60,APMR,[SWPS],مفقود,متوسط,...,نعم,البكالوريوس,الإذاعة والتلفزيون والفيلم,غير ذلك,5.00,5.0,طالب,NaN,0,100.0
2,38a11c0e-4afc-4261-9c64-e94cc0a272fb,24.0,ذكر,منطقة الرياض,الرياض,e006900d-05a9-4c2b-a36f-0ffb9fce44cd,APMR,[APMR],مفقود,متوسط,...,نعم,البكالوريوس,تقنية معلومات,تكنولوجيا الاتصالات والمعلومات,3.50,5.0,موظف,NaN,0,70.0
3,1693e85b-f80e-40ce-846f-395ddcece6d3,23.0,ذكر,منطقة الرياض,الرياض,2ec15f6b-233b-428a-b9f5-e40bc8d14cf9,TOSL,[TOSL],مفقود,مفقود,...,نعم,البكالوريوس,حوسبة تطبيقية - (مسار شبكات الحاسب),تكنولوجيا الاتصالات والمعلومات,3.55,5.0,خريج,NaN,0,71.0
4,98a0e8d0-5f80-4634-afd8-322aa0902863,23.0,ذكر,منطقة الرياض,الرياض,d32da0e9-1aed-48c3-992d-a22f9ccc741e,CAUF,[SWPS],تقليدية,متوسط,...,لا,البكالوريوس,نظم المعلومات الحاسوبية,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,موظف,NaN,0,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6543,cd196579-9590-441b-8787-41078f3cee25,31.0,أنثى,منطقة الرياض,الرياض,4f8c696a-b783-4d40-9776-105f6d3bd624,CAUF,[SWPS],مفقود,مفقود,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.40,5.0,موظف,NaN,0,88.0
6544,37bfc11c-ff8c-42dc-9cf9-0d13bb8f7131,27.0,أنثى,منطقة القصيم,بريدة,e94942dd-8684-4746-97ae-df567b9b0a4a,PCRF,[PCRF],مفقود,مبتدئ,...,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,4.46,5.0,موظف,NaN,0,89.2
6545,fc114302-a79f-439f-a08b-fe0a51cf839e,24.0,أنثى,منطقة الرياض,الرياض,02ae0b47-64a6-47a1-b3c5-c0e4df393c30,PCRF,[PCRF],تقليدية,مبتدئ,...,لا,البكالوريوس,نظم المعلومات,تكنولوجيا الاتصالات والمعلومات,4.93,5.0,موظف,دوام كامل,1,98.6
6546,4b6d9a36-4402-4c75-bc3a-fca927dbaf65,25.0,ذكر,منطقة الرياض,الرياض,9b4cedaa-fac0-4eac-aa4b-b05b6a0c97ff,PCRF,[PCRF],مفقود,متوسط,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.00,4.0,غير موظف,تدريب,0,100.0
6547,008f3386-0d43-45a4-8372-b282e5a0101a,37.0,أنثى,منطقة الرياض,الرياض,d8fbc53c-e042-4e45-b8c7-42b4ad0528ee,CAUF,[CAUF],مفقود,مبتدئ,...,نعم,الماجستير,دراسات وقضايا معاصرة,تكنولوجيا الاتصالات والمعلومات,4.32,5.0,موظف,NaN,0,86.4

In [192]:
df['Education Speaciality'].value_counts()

Education Speaciality
علوم حاسب                            2297
تقنية المعلومات                       705
نظم المعلومات                         453
نظم معلومات                           450
تقنية معلومات                         305
                                     ...
Beng Computer Systems Engineering       1
نحت، فنون بصرية                         1
Public Administration                   1
Information Science                     1
Electrical Engineer                     1
Name: count, Length: 594, dtype: int64

In [193]:
df.tail(20)

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Y,Degree_Score_Pct
6528,d122eee8-34af-40bc-891b-05890579b919,38.0,ذكر,منطقة الرياض,الرياض,60494e5b-b20a-4440-ab75-0fd257748dcc,TOSL,[TOSL],داعمة,متقدم,...,نعم,البكالوريوس,تقنية معلزمات,تكنولوجيا الاتصالات والمعلومات,2.55,4.0,موظف,NaN,0,63.75
6529,80c81dcb-f97b-41e0-a124-ae3e33df8722,25.0,ذكر,منطقة الرياض,الرياض,bf68a9ad-0543-4e6e-8a42-695953db697a,CAUF,[SWPS],مفقود,مفقود,...,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,2.47,4.0,موظف,تدريب,0,61.75
6530,e2c2cea7-1e3e-4eb8-a31d-0e93f3e20171,24.0,ذكر,المنطقة الشرقية,حفر الباطن,013916fa-85bd-46bc-80c8-f37c036fd142,PCRF,[PCRF],مفقود,متقدم,...,نعم,البكالوريوس,هندسة برمجيات,تكنولوجيا الاتصالات والمعلومات,3.38,4.0,خريج,NaN,0,84.50
6531,e5474382-17ae-436a-9a65-5237e434d881,38.0,ذكر,منطقة الرياض,الرياض,6a7a8fb3-0175-44e2-b652-a9f94fb612ad,GRST,[INFA],مفقود,متوسط,...,لا,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,2.70,5.0,موظف,NaN,1,54.00
6532,10c6c83c-50a4-454d-96b1-b7274bc12435,29.0,أنثى,منطقة مكة المكرمة,جدة,f525fd4a-d0bd-4278-b69b-1824604d6092,SERU,[ERST],تقليدية,متوسط,...,لا,البكالوريوس,الأحياء,غير ذلك,2.00,4.0,غير موظف,دوام كامل,1,50.00
6533,254df5c6-c0a5-4826-8b7e-19ac4aa34288,50.0,أنثى,منطقة الرياض,الرياض,257f416e-5009-4280-957b-fcd7212b615a,APMR,[APMR],ناشئة,مبتدئ,...,لا,الدكتوراه,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,4.82,5.0,موظف,NaN,0,96.40
6534,7cebba8b-26eb-4f2c-b6d0-abf5acb19bf7,35.0,أنثى,منطقة الرياض,الرياض,0d12d5ef-7965-4a0d-a18c-7cc826c4f971,APMR,[SRTA],داعمة,مبتدئ,...,لا,الماجستير,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,موظف,NaN,1,80.00
6535,dffea31b-9abd-460c-a912-2818fa53e641,23.0,أنثى,المنطقة الشرقية,الدمام,2e4a37aa-c299-4d79-83f7-242878de4acf,CAUF,[SWPS],مفقود,مفقود,...,نعم,البكالوريوس,نظم معلومات,تكنولوجيا الاتصالات والمعلومات,4.20,5.0,خريج,NaN,0,84.00
6536,1454b136-fe45-4b34-8b04-2af85635b626,21.0,ذكر,منطقة نجران,نجران,dd948935-4e37-4454-81f2-13d75c10cd69,PCRF,[PCRF],مفقود,مفقود,...,لا,الدبلوم,دعم فني,تكنولوجيا الاتصالات والمعلومات,4.96,5.0,طالب,NaN,1,99.20
6537,dacd9f4d-9179-4649-8b54-6ef8104e3d46,24.0,ذكر,منطقة الرياض,الرياض,c2e3fed5-4898-4b06-b141-fdd3cfb8db9a,CAUF,[CRDP],مفقود,مفقود,...,لا,البكالوريوس,الشريعة,تكنولوجيا الاتصالات والمعلومات,4.42,5.0,موظف,NaN,1,88.40
6538,63eb0d6f-af0e-4e31-b27f-d1ee9d8d28aa,22.0,أنثى,منطقة الرياض,الرياض,786daedd-7fb3-4c4f-9c24-e19768b39ece,APMR,[APMR],مفقود,متوسط,...,لا,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,3.52,5.0,موظف,NaN,0,70.40
6539,b2efda70-c536-4dd8-930d-be6c75602d50,21.0,ذكر,منطقة عسير,أبها,02ae0b47-64a6-47a1-b3c5-c0e4df393c30,PCRF,[PCRF],تقليدية,مبتدئ,...,نعم,البكالوريوس,نظم معلومات,تكنولوجيا الاتصالات والمعلومات,4.25,5.0,طالب,NaN,0,85.00
6540,be0e4c24-bc3e-45de-ba4c-f9968e8b295b,29.0,أنثى,منطقة الرياض,الرياض,b0ee753e-5f35-4dc8-ae46-03af557569c0,APMR,[APMR],مفقود,متوسط,...,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,3.81,4.0,موظف,NaN,0,95.25
6541,efa0a130-d1a3-4b21-b6bd-656e612e289a,22.0,ذكر,منطقة مكة المكرمة,جدة,774699c7-15e8-484e-9045-efe5905866aa,APMR,[SRTA],مفقود,متوسط,...,نعم,البكالوريوس,نظم المعلومات,تكنولوجيا الاتصالات والمعلومات,4.15,5.0,غير موظف,دوام جزئي,0,83.00
6542,537cbf47-e5c8-4ff8-a636-ea3aa34c36b0,25.0,أنثى,منطقة الرياض,الرياض,bf68a9ad-0543-4e6e-8a42-695953db697a,CAUF,[SWPS],مفقود,مفقود,...,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,4.20,5.0,موظف,NaN,0,84.00
6543,cd196579-9590-441b-8787-41078f3cee25,31.0,أنثى,منطقة الرياض,الرياض,4f8c696a-b783-4d40-9776-105f6d3bd624,CAUF,[SWPS],مفقود,مفقود,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.40,5.0,موظف,NaN,0,88.00
6544,37bfc11c-ff8c-42dc-9cf9-0d13bb8f7131,27.0,أنثى,منطقة القصيم,بريدة,e94942dd-8684-4746-97ae-df567b9b0a4a,PCRF,[PCRF],مفقود,مبتدئ,...,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,4.46,5.0,موظف,NaN,0,89.20
6545,fc114302-a79f-439f-a08b-fe0a51cf839e,24.0,أنثى,منطقة الرياض,الرياض,02ae0b47-64a6-47a1-b3c5-c0e4df393c30,PCRF,[PCRF],تقليدية,مبتدئ,...,لا,البكالوريوس,نظم المعلومات,تكنولوجيا الاتصالات والمعلومات,4.93,5.0,موظف,دوام كامل,1,98.60
6546,4b6d9a36-4402-4c75-bc3a-fca927dbaf65,25.0,ذكر,منطقة الرياض,الرياض,9b4cedaa-fac0-4eac-aa4b-b05b6a0c97ff,PCRF,[PCRF],مفقود,متوسط,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.00,4.0,غير موظف,تدريب,0,100.00
6547,008f3386-0d43-45a4-8372-b282e5a0101a,37.0,أنثى,منطقة الرياض,الرياض,d8fbc53c-e042-4e45-b8c7-42b4ad0528ee,CAUF,[CAUF],مفقود,مبتدئ,...,نعم,الماجستير,دراسات وقضايا معاصرة,تكنولوجيا الاتصالات والمعلومات,4.32,5.0,موظف,NaN,0,86.40

In [ ]:
#راح تاثر على دقه المودل
#ايضا دراسات وقضايا معاصرة	 - الدعم الفني
dfwrong = df[df['Education Speaciality']=='الشريعة']
dfwrong

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Y,Degree_Score_Pct
1702,f37b4917-abb9-41fe-af05-5c9b9b9b7a08,30.0,أنثى,منطقة الرياض,الرياض,5bc0a5dc-023b-42f1-b93a-852605abdbc9,CAUF,[SWPS],تقليدية,مبتدئ,...,نعم,البكالوريوس,الشريعة,غير ذلك,4.00,5.0,موظف,دوام كامل,0,80.0
2995,3f102fcf-b26a-45bc-8fb5-f394879d5560,22.0,ذكر,منطقة الرياض,الرياض,d252b2be-cb8f-4b62-8fae-715cf4a51c71,APMR,[SRTA],مفقود,مفقود,...,لا,البكالوريوس,الشريعة,تكنولوجيا الاتصالات والمعلومات,4.52,5.0,موظف,NaN,0,90.4
3055,f8c07a2a-8f81-465d-84e6-698f227a06cb,23.0,ذكر,منطقة الرياض,الرياض,4957a013-46a7-419c-93d5-ebf3741ab2a1,PCRF,[PCRF],تقليدية,مبتدئ,...,لا,البكالوريوس,الشريعة,تكنولوجيا الاتصالات والمعلومات,4.80,5.0,موظف,NaN,0,96.0
4297,50871f41-ca02-4809-b3b9-df1f04b0b282,29.0,أنثى,منطقة مكة المكرمة,الطائف,ce3562c8-8d27-4ffb-8dfc-e1dd4527b32a,PCRF,[PCRF],تقليدية,مبتدئ,...,لا,البكالوريوس,الشريعة,تكنولوجيا الاتصالات والمعلومات,2.10,4.0,غير موظف,NaN,1,52.5
4524,dacd9f4d-9179-4649-8b54-6ef8104e3d46,24.0,ذكر,منطقة الرياض,الرياض,bdf6a9e2-9be7-4aaa-a117-d7fb3c90c53f,CAUF,[CRDP],ناشئة,مبتدئ,...,لا,البكالوريوس,الشريعة,تكنولوجيا الاتصالات والمعلومات,4.42,5.0,موظف,NaN,1,88.4
4749,f37b4917-abb9-41fe-af05-5c9b9b9b7a08,30.0,أنثى,منطقة الرياض,الرياض,3ec67853-6b57-48cc-9bc6-956e286a7c65,CAUF,[ERST],تقليدية,متوسط,...,نعم,البكالوريوس,الشريعة,غير ذلك,4.00,5.0,موظف,دوام كامل,1,80.0
6339,f37b4917-abb9-41fe-af05-5c9b9b9b7a08,30.0,أنثى,منطقة الرياض,الرياض,4ad7a7dc-abcf-43fa-b2e3-07095e083661,PCRF,[PCRF],مفقود,متقدم,...,نعم,البكالوريوس,الشريعة,غير ذلك,4.00,5.0,موظف,دوام كامل,1,80.0
6537,dacd9f4d-9179-4649-8b54-6ef8104e3d46,24.0,ذكر,منطقة الرياض,الرياض,c2e3fed5-4898-4b06-b141-fdd3cfb8db9a,CAUF,[CRDP],مفقود,مفقود,...,لا,البكالوريوس,الشريعة,تكنولوجيا الاتصالات والمعلومات,4.42,5.0,موظف,NaN,1,88.4

In [ ]:
##we will filled the missing data inJob Type with مفقود
df['Job Type'] = df['Job Type'].fillna('مفقود')
df

,Student ID,Age,Gender,Home Region,Home City,Program ID,Program Main Category Code,Program Sub Category Code,Technology Type,Program Skill Level,...,Completed Degree,Level of Education,Education Speaciality,College,University Degree Score,University Degree Score System,Employment Status,Job Type,Y,Degree_Score_Pct
0,4f14c50d-162e-4a15-9cf0-ec129c33bcf0,37.0,ذكر,منطقة الرياض,الرياض,453686d8-4023-4506-b2df-fac8b059ac26,PCRF,[PCRF],مفقود,مفقود,...,نعم,البكالوريوس,هندسة حاسب,تكنولوجيا الاتصالات والمعلومات,2.44,4.0,غير موظف,مفقود,0,61.0
1,0599d409-876b-41a5-af05-749ef0e77d32,21.0,ذكر,منطقة عسير,خميس مشيط,cc8e4e42-65d5-4fa1-82f9-6c6c2d508b60,APMR,[SWPS],مفقود,متوسط,...,نعم,البكالوريوس,الإذاعة والتلفزيون والفيلم,غير ذلك,5.00,5.0,طالب,مفقود,0,100.0
2,38a11c0e-4afc-4261-9c64-e94cc0a272fb,24.0,ذكر,منطقة الرياض,الرياض,e006900d-05a9-4c2b-a36f-0ffb9fce44cd,APMR,[APMR],مفقود,متوسط,...,نعم,البكالوريوس,تقنية معلومات,تكنولوجيا الاتصالات والمعلومات,3.50,5.0,موظف,مفقود,0,70.0
3,1693e85b-f80e-40ce-846f-395ddcece6d3,23.0,ذكر,منطقة الرياض,الرياض,2ec15f6b-233b-428a-b9f5-e40bc8d14cf9,TOSL,[TOSL],مفقود,مفقود,...,نعم,البكالوريوس,حوسبة تطبيقية - (مسار شبكات الحاسب),تكنولوجيا الاتصالات والمعلومات,3.55,5.0,خريج,مفقود,0,71.0
4,98a0e8d0-5f80-4634-afd8-322aa0902863,23.0,ذكر,منطقة الرياض,الرياض,d32da0e9-1aed-48c3-992d-a22f9ccc741e,CAUF,[SWPS],تقليدية,متوسط,...,لا,البكالوريوس,نظم المعلومات الحاسوبية,تكنولوجيا الاتصالات والمعلومات,4.00,5.0,موظف,مفقود,0,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6543,cd196579-9590-441b-8787-41078f3cee25,31.0,أنثى,منطقة الرياض,الرياض,4f8c696a-b783-4d40-9776-105f6d3bd624,CAUF,[SWPS],مفقود,مفقود,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.40,5.0,موظف,مفقود,0,88.0
6544,37bfc11c-ff8c-42dc-9cf9-0d13bb8f7131,27.0,أنثى,منطقة القصيم,بريدة,e94942dd-8684-4746-97ae-df567b9b0a4a,PCRF,[PCRF],مفقود,مبتدئ,...,نعم,البكالوريوس,علوم حاسب,تكنولوجيا الاتصالات والمعلومات,4.46,5.0,موظف,مفقود,0,89.2
6545,fc114302-a79f-439f-a08b-fe0a51cf839e,24.0,أنثى,منطقة الرياض,الرياض,02ae0b47-64a6-47a1-b3c5-c0e4df393c30,PCRF,[PCRF],تقليدية,مبتدئ,...,لا,البكالوريوس,نظم المعلومات,تكنولوجيا الاتصالات والمعلومات,4.93,5.0,موظف,دوام كامل,1,98.6
6546,4b6d9a36-4402-4c75-bc3a-fca927dbaf65,25.0,ذكر,منطقة الرياض,الرياض,9b4cedaa-fac0-4eac-aa4b-b05b6a0c97ff,PCRF,[PCRF],مفقود,متوسط,...,نعم,البكالوريوس,تقنية المعلومات,تكنولوجيا الاتصالات والمعلومات,4.00,4.0,غير موظف,تدريب,0,100.0
6547,008f3386-0d43-45a4-8372-b282e5a0101a,37.0,أنثى,منطقة الرياض,الرياض,d8fbc53c-e042-4e45-b8c7-42b4ad0528ee,CAUF,[CAUF],مفقود,مبتدئ,...,نعم,الماجستير,دراسات وقضايا معاصرة,تكنولوجيا الاتصالات والمعلومات,4.32,5.0,موظف,مفقود,0,86.4

In [198]:
df.isna().sum()

Student ID                        0
Age                               0
Gender                            0
Home Region                       0
Home City                         0
Program ID                        0
Program Main Category Code        0
Program Sub Category Code         0
Technology Type                   0
Program Skill Level               0
Program Presentation Method       0
Program Start Date                0
Program End Date                  0
Program Days                      0
Completed Degree                  0
Level of Education                0
Education Speaciality             0
College                           0
University Degree Score           0
University Degree Score System    0
Employment Status                 0
Job Type                          0
Y                                 0
Degree_Score_Pct                  0
dtype: int64